from importlib import import_module

from graph_engine.runtime.checkpoint import Checkpoint, load_checkpoint, write_checkpoint
from graph_engine.runtime.effects import (
    EffectExecutor,
    EffectPublicationIndeterminate,
    EffectSettlement,
    EffectStateError,
    needs_settlement,
)
from graph_engine.runtime.events import (
    EffectApplyStarted,
    EffectIntentCommitted,
    EffectReceiptRecorded,
    EventEnvelope,
    FailureKind,
    GraphCompleted,
    GraphFailed,
    GraphStarted,
    InterruptResumed,
    InvocationFinished,
    InvocationStarted,
    NodeActivated,
    NodeCompleted,
    NodeFailed,
    NodeInterrupted,
    RuntimeEvent,
    RuntimeFailure,
    TaskActivityBound,
    TaskActivityCancelRequested,
    TaskActivityDispatchStarted,
    TaskActivityPrepared,
    TaskActivityTerminalObserved,
    TaskAttemptCommittedEffectFailed,
    TaskAttemptFailed,
    TaskAttemptStarted,
    TaskAttemptStopped,
    TaskAttemptSucceeded,
    TaskCommitPrepared,
    TaskLeaseAcquired,
    TaskLeaseAdopted,
    TaskLeaseHeartbeat,
    TokenConsumed,
    TokenOffered,
    TaskFailure,
)
from graph_engine.runtime.ledger import (
    Ledger,
    LedgerConflictError,
    LedgerError,
    LedgerIntegrityError,
    MAX_SEQUENCE,
)
from graph_engine.runtime.invocation_lock import (
    InvocationDrift,
    authenticate_invocation_lock,
    install_invocation_lock_at,
    read_invocation_lock_at,
)
from graph_engine.runtime.models import (
    ActivationRecord,
    AttemptRecord,
    AttemptStatus,
    EffectRecord,
    FoldCursor,
    GraphInstanceRecord,
    InvocationProjection,
    PendingInterrupt,
    PlanResult,
    PlannedTask,
    PreparedTaskCommit,
    ProjectionError,
    RecoveryResult,
    TokenRecord,
    fold_events,
)
from graph_engine.runtime.planner import PlanningError, activation_id, plan_next, task_id
from graph_engine.runtime.seed import (
    EMPTY_RUNTIME_AUTHORIZATION_DIGEST,
    InvocationSeed,
    empty_invocation_seed,
)
from graph_engine.plugin_api import (
    PromotionReceipt,
    StagedFile,
    StagedWriteSet,
    TaskWorkspaceBinding,
    TaskWorkspaceIdentity,
)

_LAZY_EXPORTS = {
    "AttemptWorkspaceLost": "graph_engine.runtime.activity",
    "LedgerTaskActivityPort": "graph_engine.runtime.activity",
    "TaskActivityConflict": "graph_engine.runtime.activity",
    "TaskActivityIndeterminate": "graph_engine.runtime.activity",
    "TaskActivityProtocolViolation": "graph_engine.runtime.activity",
    "TaskActivityRecoveryUnsupported": "graph_engine.runtime.activity",
    "TaskActivityReferenceInvalid": "graph_engine.runtime.activity",
    "AttemptRootDescriptor": "graph_engine.runtime.host_protocol",
    "TaskActivityRpcIdentity": "graph_engine.runtime.host_protocol",
    "TaskExecutionHost": "graph_engine.runtime.host_protocol",
    "TaskHostCancelCall": "graph_engine.runtime.host_protocol",
    "TaskHostCallIdentity": "graph_engine.runtime.host_protocol",
    "TaskHostCallResult": "graph_engine.runtime.host_protocol",
    "TaskHostExecuteCall": "graph_engine.runtime.host_protocol",
    "TaskHostReconcileCall": "graph_engine.runtime.host_protocol",
    "TaskHostTerminalReceipt": "graph_engine.runtime.host_protocol",
    "authorized_secret_port": "graph_engine.runtime.host_protocol",
    "PromotionPublicationIndeterminate": "graph_engine.runtime.task_workspace",
    "TaskWorkspaceStore": "graph_engine.runtime.task_workspace",
    "TaskWorkspaceViolation": "graph_engine.runtime.task_workspace",
    "StartSpec": "graph_engine.runtime.driver",
    "acquire_invocation": "graph_engine.runtime.driver",
    "Engine": "graph_engine.runtime.engine",
    "EngineConflictError": "graph_engine.runtime.engine",
    "EngineError": "graph_engine.runtime.engine",
    "EnginePublicationIndeterminate": "graph_engine.runtime.engine",
    "InvocationHandle": "graph_engine.runtime.engine",
    "RunResult": "graph_engine.runtime.engine",
    "AttemptResult": "graph_engine.runtime.scheduler",
    "Clock": "graph_engine.runtime.scheduler",
    "FakeClock": "graph_engine.runtime.scheduler",
    "LedgerPublicationIndeterminate": "graph_engine.runtime.scheduler",
    "Lease": "graph_engine.runtime.scheduler",
    "LeaseUnavailableError": "graph_engine.runtime.scheduler",
    "Scheduler": "graph_engine.runtime.scheduler",
    "SchedulerStateError": "graph_engine.runtime.scheduler",
    "SystemClock": "graph_engine.runtime.scheduler",
    "select_wave": "graph_engine.runtime.scheduler",
}


def __getattr__(name: str) -> object:
    module_name = _LAZY_EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(name)
    return getattr(import_module(module_name), name)


__all__ = [
    "ActivationRecord",
    "AttemptResult",
    "AttemptRecord",
    "AttemptStatus",
    "AttemptWorkspaceLost",
    "Checkpoint",
    "Clock",
    "EventEnvelope",
    "EffectApplyStarted",
    "EffectExecutor",
    "EffectIntentCommitted",
    "EffectPublicationIndeterminate",
    "EffectReceiptRecorded",
    "EffectRecord",
    "EffectSettlement",
    "EffectStateError",
    "Engine",
    "EngineConflictError",
    "EngineError",
    "EnginePublicationIndeterminate",
    "FailureKind",
    "FakeClock",
    "FoldCursor",
    "GraphCompleted",
    "GraphFailed",
    "GraphInstanceRecord",
    "GraphStarted",
    "InterruptResumed",
    "InvocationFinished",
    "InvocationHandle",
    "InvocationDrift",
    "InvocationProjection",
    "InvocationStarted",
    "Ledger",
    "LedgerConflictError",
    "LedgerError",
    "LedgerIntegrityError",
    "LedgerPublicationIndeterminate",
    "Lease",
    "LeaseUnavailableError",
    "LedgerTaskActivityPort",
    "MAX_SEQUENCE",
    "NodeActivated",
    "NodeCompleted",
    "NodeFailed",
    "NodeInterrupted",
    "PendingInterrupt",
    "PlanResult",
    "PlannedTask",
    "PlanningError",
    "PromotionPublicationIndeterminate",
    "PreparedTaskCommit",
    "ProjectionError",
    "RecoveryResult",
    "RuntimeEvent",
    "RunResult",
    "RuntimeFailure",
    "Scheduler",
    "SchedulerStateError",
    "StartSpec",
    "SystemClock",
    "TaskActivityBound",
    "TaskActivityCancelRequested",
    "TaskActivityConflict",
    "TaskActivityDispatchStarted",
    "TaskActivityIndeterminate",
    "TaskActivityPrepared",
    "TaskActivityProtocolViolation",
    "TaskActivityRecoveryUnsupported",
    "TaskActivityReferenceInvalid",
    "TaskActivityTerminalObserved",
    "TaskActivityRpcIdentity",
    "TaskExecutionHost",
    "TaskAttemptCommittedEffectFailed",
    "TaskAttemptFailed",
    "TaskFailure",
    "TaskAttemptStarted",
    "TaskAttemptStopped",
    "TaskAttemptSucceeded",
    "TaskCommitPrepared",
    "TaskHostCancelCall",
    "TaskHostCallIdentity",
    "TaskHostCallResult",
    "TaskHostExecuteCall",
    "TaskHostReconcileCall",
    "TaskHostTerminalReceipt",
    "TaskWorkspaceBinding",
    "TaskWorkspaceIdentity",
    "TaskWorkspaceStore",
    "TaskWorkspaceViolation",
    "AttemptRootDescriptor",
    "TaskLeaseAcquired",
    "TaskLeaseAdopted",
    "TaskLeaseHeartbeat",
    "TokenConsumed",
    "TokenOffered",
    "TokenRecord",
    "StagedFile",
    "StagedWriteSet",
    "PromotionReceipt",
    "EMPTY_RUNTIME_AUTHORIZATION_DIGEST",
    "InvocationSeed",
    "empty_invocation_seed",
    "acquire_invocation",
    "activation_id",
    "authenticate_invocation_lock",
    "authorized_secret_port",
    "fold_events",
    "install_invocation_lock_at",
    "needs_settlement",
    "load_checkpoint",
    "plan_next",
    "read_invocation_lock_at",
    "select_wave",
    "task_id",
    "write_checkpoint",
]
