from __future__ import annotations

import base64
from collections.abc import Mapping
from dataclasses import dataclass
import fcntl
import hashlib
from io import BytesIO
import os
import re
import stat
from pathlib import Path, PurePosixPath
from typing import BinaryIO, cast
from zipfile import ZIP_DEFLATED, ZipFile, ZipInfo

import yaml
from yaml.nodes import MappingNode, Node, SequenceNode

from graph_engine.canonical import JSONValue, canonical_digest, canonical_json_bytes

from assurance_product.models import (
    ADAPTER_BINDING_RESOURCE_ID,
    ENGINE_API,
    PLUGIN_ID,
    PLUGIN_VERSION,
    BuiltDeploymentWheel,
    DeploymentBindingsV1,
    adapter_secret_handles,
)

_WHEEL_EPOCH = (1980, 1, 1, 0, 0, 0)
_FILE_MODE = 0o644
_CAPABILITY_DEPENDENCIES: tuple[tuple[str, str], ...] = (
    ("assurance.intake", "==0.3.0"),
    ("assurance.generation", "==0.3.0"),
    ("assurance.execution", "==0.3.0"),
    ("assurance.healing", "==0.3.0"),
    ("assurance.quality", "==0.3.0"),
    ("assurance.improvement", "==0.3.0"),
)
_CAPABILITY_PLUGIN_IMPORTS: tuple[tuple[str, str], ...] = (
    ("assurance_intake.plugin", "IntakePlugin"),
    ("assurance_generation.plugin", "GenerationPlugin"),
    ("assurance_execution.plugin", "ExecutionPlugin"),
    ("assurance_healing.plugin", "HealingPlugin"),
    ("assurance_quality.plugin", "QualityPlugin"),
    ("assurance_improvement.plugin", "ImprovementPlugin"),
)
_PROVIDER_MODULE = '''\
"""Authenticated deployment binding provider. Generated by the trusted builder."""

from __future__ import annotations

import json
from importlib.resources import files

from graph_engine import ENGINE_API_VERSION
from graph_engine.canonical import canonical_json_bytes
from graph_engine.plugin_api import (
    CapabilityBindingContribution,
    PluginContribution,
    PluginDependency,
    PluginDescriptor,
    ProviderSource,
    RegistryPorts,
    ResourceContribution,
    validate_contribution,
)

PLUGIN_VERSION = "1.1.0"


def _document() -> dict[str, object]:
    raw = files(__package__).joinpath("assurance-deployment-plugin.json").read_bytes()
    value = json.loads(raw.decode("utf-8"))
    if not isinstance(value, dict):
        raise ValueError("deployment declaration must be a mapping")
    contribution_raw = files(__package__).joinpath(
        "assurance-deployment-contribution.json"
    ).read_bytes()
    contribution = json.loads(contribution_raw.decode("utf-8"))
    if not isinstance(contribution, dict):
        raise ValueError("deployment contribution must be a mapping")
    value["contribution"] = contribution
    return value


class DeploymentPlugin:
    @staticmethod
    def descriptor() -> PluginDescriptor:
        document = _document()
        source = ProviderSource.model_validate(document["source"])
        descriptor_doc = document["descriptor"]
        if not isinstance(descriptor_doc, dict):
            raise ValueError("deployment descriptor must be a mapping")
        dependencies = tuple(
            PluginDependency(str(item["plugin_id"]), str(item["version_specifier"]))
            for item in descriptor_doc["dependencies"]
        )
        return PluginDescriptor(
            schema_version="1",
            source=source,
            plugin_id="assurance.product.agent",
            plugin_version=PLUGIN_VERSION,
            engine_api=ENGINE_API_VERSION,
            task_handlers=(),
            commit_validators=(),
            dependencies=dependencies,
            schemas=(),
            resources=tuple(str(item) for item in descriptor_doc["resources"]),
            effects=(),
            bindings=tuple(str(item) for item in descriptor_doc["bindings"]),
        )

    @staticmethod
    def contribute(ports: RegistryPorts) -> PluginContribution:
        if ports.engine_api != ENGINE_API_VERSION:
            raise ValueError(f"unsupported engine API: {ports.engine_api!r}")
        document = _document()
        contribution_doc = document["contribution"]
        if not isinstance(contribution_doc, dict):
            raise ValueError("deployment contribution must be a mapping")
        bindings = tuple(
            CapabilityBindingContribution(
                capability_id=str(item["capability_id"]),
                target_capability_id=str(item["target_capability_id"]),
                data=item["data"],
                resource_ids=tuple(str(resource_id) for resource_id in item["resource_ids"]),
                secret_handles=tuple(str(handle) for handle in item["secret_handles"]),
                contract_id=str(item.get("contract_id") or item["capability_id"]),
            )
            for item in contribution_doc["bindings"]
        )
        resources = tuple(
            ResourceContribution(
                resource_id=str(item["resource_id"]),
                media_type=str(item["media_type"]),
                content=canonical_json_bytes(item["content"]),
            )
            for item in contribution_doc["resources"]
        )
        contribution = PluginContribution(bindings=bindings, resources=resources)
        validate_contribution(DeploymentPlugin.descriptor(), contribution)
        return contribution
'''


class BindingBuildError(ValueError):
    """Raised when a deployment binding wheel cannot be built safely."""


@dataclass(frozen=True)
class _RenderedWheel:
    manifest_digest: str
    distribution: str
    import_package: str
    declaration_path: str
    entry_point_value: str
    wheel_name: str
    members: dict[str, bytes]


@dataclass(frozen=True)
class _OutputDirectory:
    path: Path
    fd: int
    identity: tuple[int, int]
    owner: int
    mode: int


def canonical_wheel_filename(distribution: str, version: str) -> str:
    escaped = re.sub(r"[^A-Za-z0-9]+", "_", distribution).strip("_")
    return f"{escaped}-{version}-py3-none-any.whl"


def build_deployment_wheel(manifest_path: Path, output_dir: Path) -> BuiltDeploymentWheel:
    document = _load_manifest_document(manifest_path)
    bindings = DeploymentBindingsV1.model_validate(document)
    _reject_capability_source_drift()
    rendered = _render_wheel_contents(bindings)
    wheel_bytes = _render_deterministic_wheel_bytes(rendered.members)
    directory = _open_output_directory(output_dir)
    try:
        _publish_wheel(directory, rendered.wheel_name, wheel_bytes)
        _require_stable_output_directory(directory)
        _require_final_bytes(directory, rendered.wheel_name, wheel_bytes)
    finally:
        os.close(directory.fd)
    return BuiltDeploymentWheel(
        wheel=output_dir / rendered.wheel_name,
        manifest_digest=rendered.manifest_digest,
        wheel_digest=_sha256_digest(wheel_bytes),
        distribution=rendered.distribution,
        import_package=rendered.import_package,
        entry_point_value=rendered.entry_point_value,
        declaration_path=rendered.declaration_path,
        plugin_id=PLUGIN_ID,
        plugin_version=PLUGIN_VERSION,
    )


def _load_manifest_document(manifest_path: Path) -> dict[str, object]:
    try:
        raw = manifest_path.read_text(encoding="utf-8")
    except OSError as error:
        raise BindingBuildError(f"cannot read deployment manifest: {manifest_path}") from error
    try:
        node = yaml.compose(raw, Loader=yaml.SafeLoader)
        if node is not None:
            _reject_duplicate_yaml_keys(node, set())
        value = yaml.safe_load(raw)
    except yaml.YAMLError as error:
        raise BindingBuildError("deployment manifest is not valid YAML") from error
    if not isinstance(value, dict):
        raise BindingBuildError("deployment manifest must be a complete mapping")
    return value


def _reject_duplicate_yaml_keys(node: Node, seen: set[int]) -> None:
    if id(node) in seen:
        return
    seen.add(id(node))
    if isinstance(node, MappingNode):
        keys: set[tuple[str, str]] = set()
        for key, value in node.value:
            identity = (key.tag, str(getattr(key, "value", "")))
            if identity in keys:
                raise BindingBuildError(f"duplicate YAML key: {identity[1]}")
            keys.add(identity)
            _reject_duplicate_yaml_keys(key, seen)
            _reject_duplicate_yaml_keys(value, seen)
    elif isinstance(node, SequenceNode):
        for child in node.value:
            _reject_duplicate_yaml_keys(child, seen)


def _open_output_directory(path: Path) -> _OutputDirectory:
    try:
        path.mkdir(parents=True, exist_ok=True)
        fd = os.open(
            path,
            os.O_RDONLY
            | getattr(os, "O_DIRECTORY", 0)
            | getattr(os, "O_NOFOLLOW", 0)
            | getattr(os, "O_CLOEXEC", 0),
        )
    except OSError as error:
        raise BindingBuildError("output directory must be a real directory") from error
    try:
        metadata = os.fstat(fd)
        mode = stat.S_IMODE(metadata.st_mode)
        if not stat.S_ISDIR(metadata.st_mode) or metadata.st_uid != os.geteuid() or mode & 0o022:
            raise BindingBuildError("output directory must be a trusted publication domain")
        try:
            fcntl.flock(fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except OSError as error:
            raise BindingBuildError("output directory is locked by another builder") from error
        directory = _OutputDirectory(path, fd, _file_identity(metadata), metadata.st_uid, mode)
        _require_stable_output_directory(directory)
        return directory
    except BaseException:
        os.close(fd)
        raise


def _publish_wheel(directory: _OutputDirectory, wheel_name: str, expected: bytes) -> None:
    temporary = f".{wheel_name}.publishing"
    entries = _entries(directory)
    if not entries.issubset({wheel_name, temporary}):
        raise BindingBuildError("output directory must be empty")
    if _recover_existing(directory, wheel_name, temporary, expected, entries):
        return
    try:
        fd = os.open(
            temporary,
            os.O_RDWR | os.O_CREAT | os.O_EXCL | getattr(os, "O_NOFOLLOW", 0) | getattr(os, "O_CLOEXEC", 0),
            _FILE_MODE,
            dir_fd=directory.fd,
        )
    except OSError as error:
        raise BindingBuildError("cannot safely create temporary wheel") from error
    identity = _file_identity(os.fstat(fd))

    def verify(links: int = 1) -> None:
        _require_stable_output_directory(directory)
        _require_content(directory, temporary, fd, identity, links, expected, "temporary wheel")

    try:
        _publication_cut("builder-before-file-publication")
        _require_stable_output_directory(directory)
        _require_entry(directory, temporary, fd, identity, 1, "temporary wheel")
        offset = 0
        while offset < len(expected):
            offset += os.write(fd, expected[offset:])
        os.fchmod(fd, _FILE_MODE)
        os.fsync(fd)
        verify()
        for cut in ("builder-after-file-publication", "builder-before-wheel-publication"):
            _publication_cut(cut)
            verify()
        try:
            os.link(
                temporary,
                wheel_name,
                src_dir_fd=directory.fd,
                dst_dir_fd=directory.fd,
                follow_symlinks=False,
            )
        except FileExistsError as error:
            raise BindingBuildError("published wheel path became occupied") from error
        os.fsync(directory.fd)
        _publication_cut("builder-after-wheel-publication")
        verify(2)
        _require_entry(directory, wheel_name, fd, identity, 2, "published wheel")
        os.unlink(temporary, dir_fd=directory.fd)
        os.fsync(directory.fd)
        _require_final_bytes(directory, wheel_name, expected)
        _publication_cut("builder-after-final-identity-check")
        _require_stable_output_directory(directory)
        _require_final_bytes(directory, wheel_name, expected)
    except OSError as error:
        raise BindingBuildError("cannot safely publish deterministic wheel") from error
    finally:
        os.close(fd)


def _recover_existing(
    directory: _OutputDirectory,
    wheel_name: str,
    temporary: str,
    expected: bytes,
    entries: set[str],
) -> bool:
    if wheel_name not in entries:
        if temporary in entries:
            fd, identity, links = _open_entry(directory, temporary, {1}, "temporary wheel")
            try:
                _remove_temporary(directory, temporary, fd, identity, links)
            finally:
                os.close(fd)
        return False
    final_fd, final_identity, final_links = _open_entry(directory, wheel_name, {1, 2}, "published wheel")
    try:
        _require_content(
            directory,
            wheel_name,
            final_fd,
            final_identity,
            final_links,
            expected,
            "published wheel",
        )
        if temporary in entries:
            fd, identity, links = _open_entry(directory, temporary, {1, 2}, "temporary wheel")
            try:
                if identity == final_identity:
                    if links != 2 or final_links != 2:
                        raise BindingBuildError("interrupted wheel link identity changed")
                    _require_content(directory, temporary, fd, identity, 2, expected, "temporary wheel")
                elif links != 1 or final_links != 1:
                    raise BindingBuildError("publication residue identity changed")
                _remove_temporary(directory, temporary, fd, identity, links)
            finally:
                os.close(fd)
    finally:
        os.close(final_fd)
    _require_final_bytes(directory, wheel_name, expected)
    _publication_cut("builder-after-final-identity-check")
    _require_stable_output_directory(directory)
    _require_final_bytes(directory, wheel_name, expected)
    return True


def _remove_temporary(
    directory: _OutputDirectory,
    name: str,
    fd: int,
    identity: tuple[int, int],
    links: int,
) -> None:
    _publication_cut("builder-before-stale-temp-cleanup")
    _require_stable_output_directory(directory)
    _require_entry(directory, name, fd, identity, links, "temporary wheel")
    try:
        os.unlink(name, dir_fd=directory.fd)
        os.fsync(directory.fd)
    except OSError as error:
        raise BindingBuildError("cannot remove trusted publication residue") from error


def _open_entry(
    directory: _OutputDirectory,
    name: str,
    allowed_links: set[int],
    label: str,
) -> tuple[int, tuple[int, int], int]:
    try:
        fd = os.open(
            name,
            os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0) | getattr(os, "O_CLOEXEC", 0),
            dir_fd=directory.fd,
        )
    except OSError as error:
        raise BindingBuildError(f"{label} is not a safe regular file") from error
    metadata = os.fstat(fd)
    identity = _file_identity(metadata)
    try:
        if metadata.st_nlink not in allowed_links:
            raise BindingBuildError(f"{label} is not a safe regular file")
        _require_entry(directory, name, fd, identity, metadata.st_nlink, label)
        return fd, identity, metadata.st_nlink
    except BaseException:
        os.close(fd)
        raise


def _require_entry(
    directory: _OutputDirectory,
    name: str,
    fd: int,
    identity: tuple[int, int],
    links: int,
    label: str,
) -> None:
    try:
        opened = os.fstat(fd)
        current = os.stat(name, dir_fd=directory.fd, follow_symlinks=False)
    except OSError as error:
        raise BindingBuildError(f"{label} identity changed") from error
    if any(
        not stat.S_ISREG(item.st_mode)
        or item.st_uid != directory.owner
        or item.st_nlink != links
        or stat.S_IMODE(item.st_mode) & 0o022
        or _file_identity(item) != identity
        for item in (opened, current)
    ):
        raise BindingBuildError(f"{label} identity changed")


def _require_content(
    directory: _OutputDirectory,
    name: str,
    fd: int,
    identity: tuple[int, int],
    links: int,
    expected: bytes,
    label: str,
) -> None:
    _require_entry(directory, name, fd, identity, links, label)
    before = os.fstat(fd)
    chunks: list[bytes] = []
    offset = 0
    while chunk := os.pread(fd, 1024 * 1024, offset):
        chunks.append(chunk)
        offset += len(chunk)
    after = os.fstat(fd)
    if (
        before.st_size,
        before.st_mtime_ns,
        before.st_ctime_ns,
        before.st_nlink,
    ) != (
        after.st_size,
        after.st_mtime_ns,
        after.st_ctime_ns,
        after.st_nlink,
    ):
        raise BindingBuildError(f"{label} authenticated content changed")
    _require_entry(directory, name, fd, identity, links, label)
    if b"".join(chunks) != expected:
        raise BindingBuildError(f"{label} authenticated content changed")


def _require_final_bytes(directory: _OutputDirectory, name: str, expected: bytes) -> None:
    fd, identity, links = _open_entry(directory, name, {1}, "published wheel")
    try:
        _require_content(directory, name, fd, identity, links, expected, "published wheel")
    finally:
        os.close(fd)


def _entries(directory: _OutputDirectory) -> set[str]:
    try:
        return set(os.listdir(directory.fd))
    except OSError as error:
        raise BindingBuildError("cannot inspect output directory") from error


def _file_identity(metadata: os.stat_result) -> tuple[int, int]:
    return (metadata.st_dev, metadata.st_ino)


def _require_stable_output_directory(directory: _OutputDirectory) -> None:
    try:
        opened = os.fstat(directory.fd)
        current = os.stat(directory.path, follow_symlinks=False)
    except OSError as error:
        raise BindingBuildError("output directory trust changed") from error
    if any(
        not stat.S_ISDIR(item.st_mode)
        or _file_identity(item) != directory.identity
        or item.st_uid != directory.owner
        or directory.owner != os.geteuid()
        or stat.S_IMODE(item.st_mode) != directory.mode
        or directory.mode & 0o022
        for item in (opened, current)
    ):
        raise BindingBuildError("output directory trust changed")


def _publication_cut(_fault_id: str) -> None:
    return


def _reject_capability_source_drift() -> None:
    from assurance_product.agent_contracts import AGENT_EXECUTION_CONTRACTS

    live_prepares, live_finalizes = _live_prepare_and_finalize_ids()
    expected_prepares = frozenset(
        contract.prepare_handler_id for contract in AGENT_EXECUTION_CONTRACTS.values()
    )
    expected_finalizes = frozenset(
        contract.finalize_handler_id for contract in AGENT_EXECUTION_CONTRACTS.values()
    )
    if live_prepares != expected_prepares or live_finalizes != expected_finalizes:
        raise BindingBuildError("source drift: installed prepare/finalize closure")


def _live_prepare_and_finalize_ids() -> tuple[frozenset[str], frozenset[str]]:
    handlers: list[str] = []
    for module_name, attribute in _CAPABILITY_PLUGIN_IMPORTS:
        module = __import__(module_name, fromlist=[attribute])
        plugin = getattr(module, attribute)
        handlers.extend(plugin.descriptor().task_handlers)
    prepares = frozenset(handler for handler in handlers if handler.endswith(".prepare"))
    finalizes = frozenset(handler for handler in handlers if handler.endswith(".finalize"))
    return prepares, finalizes


def _render_wheel_contents(bindings: DeploymentBindingsV1) -> _RenderedWheel:
    manifest_digest = _sha256_digest(canonical_json_bytes(bindings.model_dump(mode="json")))
    prefix = manifest_digest.removeprefix("sha256:")[:16]
    distribution = f"assurance-product-bindings-{prefix}"
    import_package = f"assurance_product_bindings_{prefix}"
    _assert_safe_zip_name(import_package)
    declaration_path = f"{import_package}/assurance-deployment-plugin.json"
    entry_point_value = f"{import_package}.provider:DeploymentPlugin"
    wheel_name = canonical_wheel_filename(distribution, PLUGIN_VERSION)
    dist_info = f"{Path(wheel_name).stem.replace('-py3-none-any', '')}.dist-info"
    declaration = _render_declaration(
        bindings,
        distribution=distribution,
        declaration_path=declaration_path,
        entry_point_value=entry_point_value,
    )
    contribution = declaration.pop("contribution")
    contribution_path = f"{import_package}/assurance-deployment-contribution.json"
    members = {
        f"{import_package}/__init__.py": b'"""Authenticated Assurance deployment bindings."""\n',
        f"{import_package}/provider.py": _PROVIDER_MODULE.encode("utf-8"),
        declaration_path: canonical_json_bytes(cast(JSONValue, declaration)) + b"\n",
        contribution_path: canonical_json_bytes(cast(JSONValue, contribution)) + b"\n",
        f"{dist_info}/METADATA": _metadata_bytes(distribution),
        f"{dist_info}/WHEEL": (
            "Wheel-Version: 1.0\n"
            "Generator: assurance-product-binding-builder/1.0.0\n"
            "Root-Is-Purelib: true\n"
            "Tag: py3-none-any\n"
        ).encode("utf-8"),
        f"{dist_info}/entry_points.txt": (
            f"[graph_engine.plugins]\ndeployment = {entry_point_value}\n"
        ).encode("utf-8"),
    }
    for name in members:
        _assert_safe_zip_name(name)
    return _RenderedWheel(
        manifest_digest=manifest_digest,
        distribution=distribution,
        import_package=import_package,
        declaration_path=declaration_path,
        entry_point_value=entry_point_value,
        wheel_name=wheel_name,
        members=members,
    )


def _render_declaration(
    bindings: DeploymentBindingsV1,
    *,
    distribution: str,
    declaration_path: str,
    entry_point_value: str,
) -> dict[str, object]:
    source = {
        "distribution": distribution,
        "version": PLUGIN_VERSION,
        "entrypoint_group": "graph_engine.plugins",
        "entrypoint_name": "deployment",
        "entrypoint_value": entry_point_value,
        "declaration_path": declaration_path,
        "import_roots": [""],
    }
    resources = _resource_documents(bindings)
    binding_docs = _binding_documents(bindings)
    resource_ids = tuple(item["resource_id"] for item in resources)
    binding_ids = tuple(item["capability_id"] for item in binding_docs)
    dependencies = [
        {"plugin_id": plugin_id, "version_specifier": specifier}
        for plugin_id, specifier in (
            *_CAPABILITY_DEPENDENCIES,
            (bindings.runtime_plugin_id, "==0.1.0"),
        )
    ]
    return {
        "kind": "plugin",
        "schema_version": "1",
        "source": source,
        "descriptor": {
            "schema_version": "1",
            "plugin_id": PLUGIN_ID,
            "plugin_version": PLUGIN_VERSION,
            "engine_api": ENGINE_API,
            "source": source,
            "dependencies": dependencies,
            "task_handlers": [],
            "commit_validators": [],
            "schemas": [],
            "effects": [],
            "resources": list(resource_ids),
            "bindings": list(binding_ids),
        },
        "contribution": {
            "bindings": list(binding_docs),
            "resources": list(resources),
        },
    }


def _resource_documents(bindings: DeploymentBindingsV1) -> tuple[dict[str, object], ...]:
    documents: list[dict[str, object]] = [
        {
            "resource_id": ADAPTER_BINDING_RESOURCE_ID,
            "media_type": "application/json",
            "content": bindings.adapter_binding.model_dump(mode="json"),
        }
    ]
    for resource_id, profile in sorted(bindings.permission_profiles.items()):
        documents.append(
            {
                "resource_id": resource_id,
                "media_type": "application/json",
                "content": profile.model_dump(mode="json"),
            }
        )
    for resource_id, policy in sorted(bindings.request_policies.items()):
        documents.append(
            {
                "resource_id": resource_id,
                "media_type": "application/json",
                "content": policy.model_dump(mode="json"),
            }
        )
    return tuple(sorted(documents, key=lambda item: str(item["resource_id"])))


def _binding_documents(bindings: DeploymentBindingsV1) -> tuple[dict[str, object], ...]:
    from assurance_product.agent_contracts import AGENT_EXECUTION_CONTRACTS

    execute_target = f"{bindings.runtime_plugin_id}.execute"
    secret_handles = list(adapter_secret_handles(bindings.adapter_binding))
    documents: list[dict[str, object]] = []
    for contract_id, job in AGENT_EXECUTION_CONTRACTS.items():
        assignment = bindings.routes[contract_id]
        agent_profile = job.agent_profile
        permission_digest = canonical_digest(
            bindings.permission_profiles[assignment.permission_profile_id].model_dump(mode="json")
        )
        policy_digest = canonical_digest(
            bindings.request_policies[assignment.request_policy_id].model_dump(mode="json")
        )
        request_config_digest = canonical_digest(
            {
                "adapter_plugin_id": bindings.runtime_plugin_id,
                "adapter_configuration_digest": bindings.adapter_binding.adapter_configuration_digest,
                "agent_profile": agent_profile,
                "provider_model": assignment.provider_model,
                "worker_profile": assignment.worker_profile,
                "permission_profile_digest": permission_digest,
                "request_policy_digest": policy_digest,
                "capability_binding_id": contract_id,
            }
        )
        documents.append(
            {
                "capability_id": contract_id,
                "target_capability_id": execute_target,
                "data": {
                    "agent_profile": agent_profile,
                    "execution": {
                        "provider_model": assignment.provider_model,
                        "worker_profile": assignment.worker_profile,
                        "permission_profile_digest": permission_digest,
                        "limits": assignment.limits.model_dump(mode="json"),
                    },
                    "request_policy_digest": policy_digest,
                    "request_config_digest": request_config_digest,
                },
                "resource_ids": [
                    assignment.permission_profile_id,
                    assignment.request_policy_id,
                ],
                "secret_handles": secret_handles,
                "contract_id": contract_id,
            }
        )
    return tuple(sorted(documents, key=lambda item: str(item["capability_id"])))


def _metadata_bytes(distribution: str) -> bytes:
    requirements = [
        "graph-engine==0.2.0",
        *(f"{name}==0.3.0" for name, _ in _CAPABILITY_DEPENDENCIES),
    ]
    lines = [
        "Metadata-Version: 2.1",
        f"Name: {distribution}",
        f"Version: {PLUGIN_VERSION}",
        "Summary: Authenticated Assurance deployment binding wheel",
        "Requires-Python: >=3.11",
        *(f"Requires-Dist: {requirement}" for requirement in requirements),
        "",
    ]
    return "\n".join(lines).encode("utf-8")


def _write_deterministic_wheel(stream: BinaryIO, members: Mapping[str, bytes]) -> None:
    record_name = next(name for name in members if name.endswith(".dist-info/METADATA")).replace(
        "METADATA", "RECORD"
    )
    _assert_safe_zip_name(record_name)
    record_lines = [
        f"{name},{_record_hash(content)},{len(content)}" for name, content in sorted(members.items())
    ]
    record_lines.append(f"{record_name},,")
    record_bytes = ("\n".join(record_lines) + "\n").encode("utf-8")
    ordered = dict(sorted(members.items()))
    ordered[record_name] = record_bytes
    names = [name for name in ordered if name != record_name]
    names.append(record_name)
    with ZipFile(stream, "w") as archive:
        for name in names:
            info = ZipInfo(filename=name, date_time=_WHEEL_EPOCH)
            info.compress_type = ZIP_DEFLATED
            info.create_system = 3
            info.external_attr = _FILE_MODE << 16
            archive.writestr(info, ordered[name], compress_type=ZIP_DEFLATED, compresslevel=9)


def _render_deterministic_wheel_bytes(members: Mapping[str, bytes]) -> bytes:
    stream = BytesIO()
    _write_deterministic_wheel(stream, members)
    return stream.getvalue()


def _record_hash(content: bytes) -> str:
    digest = hashlib.sha256(content).digest()
    return "sha256=" + base64.urlsafe_b64encode(digest).decode("ascii").rstrip("=")


def _sha256_digest(content: bytes) -> str:
    return "sha256:" + hashlib.sha256(content).hexdigest()


def _assert_safe_zip_name(name: str) -> None:
    if not name or "\\" in name or name.startswith("/") or name.endswith("/"):
        raise BindingBuildError("ZIP path escape")
    path = PurePosixPath(name)
    if path.is_absolute() or path.as_posix() != name or any(part in {"", ".", ".."} for part in path.parts):
        raise BindingBuildError("ZIP path escape")
