"""task 私有写层与内容寻址 write-set（Plan → Execute → Update 的 Execute/Update 底座）。

每个 write-capable task 在同一 committed snapshot 的私有物化副本中执行；handler
只持有 ``TaskWorkspace`` 内的路径。task 完成后，coordinator 独立计算 before/after
diff，逐条对照 ``authorization_writes`` fail closed，把新 blob 与 write-set manifest
写入 change dir 下的内容寻址对象库（``.graph-runtime/objects/sha256/<前两位>/<digest>``），
``write_set_id`` 即 manifest 规范字节的 sha256。Update 按 structural task ID 排序合并
write-sets，校验 sibling 不重叠、entry before 与 base tree 一致、canonical root 无漂移，
再以 temp-file + ``os.replace`` 幂等物化到 canonical root；partial apply 重放必收敛。

tree manifest 是按路径排序的规范 JSON，记录 ``kind``/``sha256``/executable mode 与逻辑
root 映射（``change:``/``project:``/``repo:`` → 树内前缀）。capture 排除 ``.git/``、
``.graph-runtime/``、``.worktrees/``、``.venv/``、``.opencode/``、``eval/``、
``benchmark/``、``node_modules/``、``__pycache__/``、``.pytest_cache/``、``.ruff_cache/``、
``.hypothesis/``、``htmlcov/``，
以及 change-dir coordinator 文件
（``events.jsonl``、``workflow-state.yaml``、``running-tasks.json``、
``.progression.lock``、``driver.json``、``driver.lock``）与执行期副作用文件
（``.coverage``、``db.sqlite3``[+shm/wal]）；变化的 symlink 与解析到逻辑 root 之外的路径
一律拒绝。对象库由 coordinator 独占写入，不暴露给 handler。
"""

from __future__ import annotations

import hashlib
import json
import os
import shutil
import subprocess
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Literal

from pydantic import BaseModel, ConfigDict

from assurance_agent.exceptions import AaError
from assurance_agent.workflow.graph.contracts import ResourceClaims, ResourcePath, path_covers
from assurance_agent.workflow.graph.models import ResolvedArtifact

_OBJECTS_RELPATH = Path(".graph-runtime") / "objects"
_TASKS_RELPATH = Path(".graph-runtime") / "tasks"
_TREE_MANIFEST_RELPATH = Path(".graph-runtime") / "tree.json"
_EXCLUDED_DIRS = frozenset(
    {
        ".git",
        ".graph-runtime",
        ".worktrees",
        ".venv",
        # Agent skill install roots often symlink outside the SUT (legacy aws-* /
        # opencode layouts). Real aa skills live under skills/ and are captured.
        ".opencode",
        # Eval harness outputs under the SUT (eval/out/…) are huge and not
        # product sources; capturing them stalls every GraphRuntime start.
        "eval",
        # Benchmark harness + live loop logs/status under project root. Capturing
        # them causes canonical drift when the loop rewrites *.status.json mid-run.
        "benchmark",
        "node_modules",
        "__pycache__",
        ".pytest_cache",
        ".ruff_cache",
        # Hypothesis example DB / codec caches written under the SUT during
        # fuzz/property tests; not product sources and must not enter write-sets.
        ".hypothesis",
        # pytest-cov HTML output (if enabled); binary .coverage is a file below.
        "htmlcov",
        # ORM migration files (e.g. aerich ``migrations/models/*_init.py``) are
        # regenerated by the SUT's ``init_db`` whenever the app boots in-process
        # (e.g. schemathesis ``from_asgi``) during execution. They are generated
        # runtime artifacts, not QA write-set targets, so keep them out of
        # capture/freeze or execution fails as forbidden_write on migrations/**.
        "migrations",
    }
)
# change-dir coordinator 文件：不进 tree capture，也不参与 apply drift。
# Also exclude SUT runtime side-effects from pytest/uvicorn under the project
# root (coverage data file + local sqlite), which otherwise fail freeze as
# forbidden_write / canonical drift during execution.
_EXCLUDED_FILES = frozenset(
    {
        "events.jsonl",
        "workflow-state.yaml",
        "running-tasks.json",
        ".progression.lock",
        "driver.json",
        # Ephemeral start-guard lock written by the driver around run/resume;
        # must not participate in tree capture/apply or resume repair treats
        # the live lock as canonical workspace drift.
        "driver.lock",
        ".coverage",
        "db.sqlite3",
        "db.sqlite3-shm",
        "db.sqlite3-wal",
    }
)
_HEX = frozenset("0123456789abcdef")
_GIT_TIMEOUT_S = 120
_MAX_TREE_SYMLINK_HOPS = 40


class WorkspaceError(AaError):
    """workspace/tree/write-set 完整性或授权失败；一律 fail closed。"""


# ---------------------------------------------------------------------------
# 内部模型与规范 JSON


@dataclass(frozen=True)
class _Entry:
    kind: Literal["file", "symlink"]
    sha256: str
    executable: bool = False


@dataclass(frozen=True)
class _TreeManifest:
    roots: dict[str, str]
    entries: dict[str, _Entry]
    raw: bytes


def _canonical_json(payload: Mapping[str, object]) -> bytes:
    return json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode("utf-8")


def _tree_payload(roots: Mapping[str, str], entries: Mapping[str, _Entry]) -> dict[str, object]:
    return {
        "entries": [
            {"executable": entry.executable, "kind": entry.kind, "path": path, "sha256": entry.sha256}
            for path, entry in sorted(entries.items())
        ],
        "kind": "tree",
        "roots": dict(sorted(roots.items())),
        "version": 1,
    }


def _assert_safe_prefix(prefix: object) -> str:
    if not isinstance(prefix, str) or not prefix:
        raise WorkspaceError(f"invalid tree root prefix: {prefix!r}")
    if prefix == ".":
        return prefix
    parts = prefix.split("/")
    if prefix.startswith("/") or "\\" in prefix or any(part in ("", ".", "..") for part in parts):
        raise WorkspaceError(f"unsafe tree root prefix: {prefix!r}")
    return prefix


def _resolve_tree_symlink(rel: str, target: str) -> str:
    target_path = PurePosixPath(target)
    if target_path.is_absolute():
        raise WorkspaceError(f"tree symlink target is absolute: {rel}")
    parts = list(PurePosixPath(rel).parent.parts)
    for part in target_path.parts:
        if part in ("", "."):
            continue
        if part == "..":
            if not parts:
                raise WorkspaceError(f"tree symlink escapes materialization root: {rel}")
            parts.pop()
            continue
        parts.append(part)
    if not parts:
        return "."
    return PurePosixPath(*parts).as_posix()


def _parse_tree(raw: bytes) -> _TreeManifest:
    try:
        payload = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise WorkspaceError(f"invalid tree manifest: {exc}") from exc
    if not isinstance(payload, dict) or payload.get("kind") != "tree":
        raise WorkspaceError("invalid tree manifest: missing kind")
    raw_roots = payload.get("roots")
    if not isinstance(raw_roots, dict):
        raise WorkspaceError("invalid tree manifest: roots must be a mapping")
    roots = {str(name): _assert_safe_prefix(prefix) for name, prefix in raw_roots.items()}
    raw_entries = payload.get("entries")
    if not isinstance(raw_entries, list):
        raise WorkspaceError("invalid tree manifest: entries must be a list")
    entries: dict[str, _Entry] = {}
    for item in raw_entries:
        if not isinstance(item, dict):
            raise WorkspaceError("invalid tree manifest: entry must be a mapping")
        path = item.get("path")
        kind = item.get("kind")
        sha256 = item.get("sha256")
        if not isinstance(path, str) or kind not in ("file", "symlink") or not isinstance(sha256, str):
            raise WorkspaceError(f"invalid tree manifest entry: {item!r}")
        _assert_digest(sha256)
        entries[path] = _Entry(kind=kind, sha256=sha256, executable=bool(item.get("executable", False)))
    return _TreeManifest(roots=roots, entries=entries, raw=raw)


def _assert_digest(digest: str) -> None:
    if len(digest) != 64 or any(ch not in _HEX for ch in digest):
        raise WorkspaceError(f"invalid object digest: {digest!r}")


def _is_within(path: Path, root: Path) -> bool:
    try:
        path.relative_to(root)
    except ValueError:
        return False
    return True


# ---------------------------------------------------------------------------
# 文件系统遍历（capture/freeze/apply 共用同一套排除与 symlink 规则）


def _is_excluded_name(name: str) -> bool:
    if name in _EXCLUDED_FILES:
        return True
    # pytest-cov may write host-pid variants like ``.coverage.hostname.1234``.
    return name.startswith(".coverage.")


def _is_top_level_issue_ledger(rel: str | PurePosixPath) -> bool:
    parts = PurePosixPath(rel).parts
    return (
        len(parts) == 5
        and parts[0] == "qa"
        and parts[1] in {"changes", "archive"}
        and parts[3:] == ("issues", "events.jsonl")
    )


def _is_excluded_rel(rel: str) -> bool:
    """True when any path segment is an excluded dir or the basename is excluded."""
    parts = [part for part in rel.split("/") if part and part != "."]
    if not parts:
        return False
    # Change Issue ledgers are canonical domain data, not the change-dir graph
    # coordinator ledger.  They must participate in capture/freeze/apply so a
    # later execution batch can replay all Observations and Occurrences.
    if _is_top_level_issue_ledger(rel):
        return False
    if _is_excluded_name(parts[-1]):
        return True
    return any(part in _EXCLUDED_DIRS for part in parts[:-1] or parts)


def _is_synchronized_ledger_rel(
    roots: Mapping[str, str],
    rel: str,
    synchronized: Sequence[ResourcePath],
) -> bool:
    """Project ledger JSONL under synchronized prefixes must still publish.

    Basename ``events.jsonl`` is globally capture-excluded (change-dir coordinator),
    but ``qa/issues/events.jsonl`` / ``qa/improvements/events.jsonl`` are canonical
    ledgers and must ride synchronized write-sets.
    """
    if not synchronized:
        return False
    parts = [part for part in rel.split("/") if part and part != "."]
    if not parts or parts[-1] != "events.jsonl":
        return False
    try:
        logical = ResourcePath.parse(_canonical_logical(roots, rel))
    except WorkspaceError:
        return False
    return logical.root == "project" and any(path_covers(prefix, logical) for prefix in synchronized)


def _walk(root: Path, *, keep_change_dir: Path | None = None) -> dict[str, _Entry]:
    root = root.resolve()
    keep_prefix: str | None = None
    if keep_change_dir is not None:
        keep = keep_change_dir.resolve()
        if _is_within(keep, root):
            keep_prefix = keep.relative_to(root).as_posix()
    entries: dict[str, _Entry] = {}

    def visit(directory: Path, prefix: str) -> None:
        with os.scandir(directory) as children:
            for child in children:
                rel = f"{prefix}{child.name}"
                if _is_excluded_rel(rel):
                    continue
                # Sibling qa/changes/<other-id>/ must not enter this change's tree —
                # the loop keeps multiple in-flight change dirs under one SUT.
                if (
                    keep_prefix is not None
                    and rel.startswith("qa/changes/")
                    and rel != keep_prefix
                    and not rel.startswith(f"{keep_prefix}/")
                ):
                    continue
                # Excluded roots are skipped whatever their kind, matching
                # ``_is_excluded_rel``: tooling often leaves ``.venv`` as a symlink to a
                # shared interpreter, which must not fail the walk for pointing outside.
                if child.name in _EXCLUDED_DIRS:
                    continue
                if child.is_dir(follow_symlinks=False):
                    visit(Path(child.path), f"{rel}/")
                    continue
                if child.is_symlink():
                    target = os.readlink(child.path)
                    resolved = (Path(child.path).parent / target).resolve()
                    if not _is_within(resolved, root):
                        raise WorkspaceError(f"symlink resolves outside its logical root: {rel}")
                    data = target.encode("utf-8")
                    entries[rel] = _Entry(kind="symlink", sha256=hashlib.sha256(data).hexdigest())
                    continue
                if child.is_file(follow_symlinks=False):
                    data = Path(child.path).read_bytes()
                    executable = bool(child.stat(follow_symlinks=False).st_mode & 0o100)
                    entries[rel] = _Entry(
                        kind="file", sha256=hashlib.sha256(data).hexdigest(), executable=executable
                    )
                    continue
                raise WorkspaceError(f"unsupported filesystem entry: {rel}")

    visit(root, "")
    return entries


def _install_file(path: Path, data: bytes, executable: bool) -> None:
    """temp-file + os.replace 落盘并固定 mode；apply 阶段的最小写入单元。"""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.parent / f"{path.name}.tmp.{os.getpid()}"
    try:
        tmp.write_bytes(data)
        # The replacement must publish content and mode as one filesystem state.
        # Otherwise a crash after replace leaves content-at-target with mode-at-base,
        # which is neither side of the replay comparison.
        os.chmod(tmp, 0o755 if executable else 0o644)
        os.replace(tmp, path)
    finally:
        tmp.unlink(missing_ok=True)


def _same_file_content(left: _Entry | None, right: _Entry | None) -> bool:
    """Whether two entries differ, if at all, only in executable mode."""
    return (
        left is not None
        and right is not None
        and left.kind == "file"
        and right.kind == "file"
        and left.sha256 == right.sha256
    )


def _path_matches_entry(path: Path, entry: _Entry) -> bool:
    """Whether on-disk bytes match a tree/write-set file entry."""
    if entry.kind != "file" or not path.is_file():
        return False
    return hashlib.sha256(path.read_bytes()).hexdigest() == entry.sha256


def _prune_empty_parents(path: Path, stop: Path) -> None:
    parent = path.parent
    while parent != stop and _is_within(parent, stop):
        try:
            parent.rmdir()
        except OSError:
            return
        parent = parent.parent


def _validated_synchronized_paths(
    paths: Sequence[ResourcePath | str],
) -> tuple[ResourcePath, ...]:
    validated: dict[str, ResourcePath] = {}
    for value in paths:
        path = ResourcePath.parse(value) if isinstance(value, str) else value
        if path.root != "project":
            raise WorkspaceError(f"synchronized path must use the project root: {path.root}:{path.pattern}")
        wildcard_segments = [segment for segment in path.segments if "*" in segment]
        if wildcard_segments and not (wildcard_segments == ["**"] and path.segments[-1] == "**"):
            raise WorkspaceError(
                f"synchronized path must be a concrete file or directory prefix: {path.pattern}"
            )
        validated[path.pattern] = path
    return tuple(validated[key] for key in sorted(validated))


def _matches_synchronized_path(
    roots: Mapping[str, str],
    rel: str,
    synchronized: Sequence[ResourcePath],
) -> bool:
    prefix = roots.get("project")
    if prefix is None:
        raise WorkspaceError("tree manifest missing project logical root")
    prefix = _assert_safe_prefix(prefix)
    if prefix == ".":
        logical_rel = rel
    elif rel.startswith(f"{prefix}/"):
        logical_rel = rel[len(prefix) + 1 :]
    else:
        return False
    logical = ResourcePath.parse(f"project:{logical_rel}")
    return any(path_covers(path, logical) for path in synchronized)


def _capture_synchronized_entries(
    project_root: Path,
    roots: Mapping[str, str],
    synchronized: Sequence[ResourcePath],
    *,
    active_change_dir: Path | None = None,
) -> dict[str, tuple[_Entry, bytes]]:
    captured: dict[str, tuple[_Entry, bytes]] = {}
    for path in synchronized:
        rel_pattern = _physical_for(roots, path)
        if path.segments[-1] == "**":
            directory_rel = rel_pattern.removesuffix("/**")
            directory = project_root / directory_rel
            if not _is_within(directory.parent.resolve(), project_root):
                raise WorkspaceError(f"synchronized directory escapes project root: {path.pattern}")
            if directory.is_symlink():
                raise WorkspaceError(f"synchronized directory cannot be a symlink: {path.pattern}")
            if not directory.exists():
                continue
            if not directory.is_dir():
                raise WorkspaceError(f"synchronized prefix is not a directory: {path.pattern}")
            for child_rel, entry in _walk(directory).items():
                full_rel = f"{directory_rel}/{child_rel}"
                source = project_root / full_rel
                if entry.kind == "file":
                    data = source.read_bytes()
                else:
                    data = os.readlink(source).encode("utf-8")
                if hashlib.sha256(data).hexdigest() != entry.sha256:
                    raise WorkspaceError(f"synchronized path changed during capture: {full_rel}")
                captured[full_rel] = (entry, data)
            # Ledger JSONL is basename-excluded from _walk; include it for live overlay.
            events_rel = f"{directory_rel}/events.jsonl" if directory_rel else "events.jsonl"
            events_captured = _entry_and_bytes_at(project_root, events_rel)
            if events_captured is not None:
                captured[events_rel] = events_captured
            # The normal tree walk excludes every events.jsonl basename because
            # the active Change coordinator mutates its ledger during execution.
            # A synchronized Retro snapshot still needs immutable sibling Change
            # workflow and Issue ledgers, so capture those two known locations
            # explicitly while keeping the active coordinator ledger excluded.
            if directory_rel in {"qa/changes", "qa/archive"}:
                active = active_change_dir.resolve() if active_change_dir is not None else None
                for change_dir in sorted(path for path in directory.iterdir() if path.is_dir()):
                    for suffix in (Path("events.jsonl"), Path("issues/events.jsonl")):
                        ledger = change_dir / suffix
                        if active is not None and ledger.resolve() == (active / suffix).resolve():
                            continue
                        ledger_rel = ledger.relative_to(project_root).as_posix()
                        ledger_captured = _entry_and_bytes_at(project_root, ledger_rel)
                        if ledger_captured is not None:
                            captured[ledger_rel] = ledger_captured
            continue
        file_captured = _entry_and_bytes_at(project_root, rel_pattern)
        if file_captured is not None:
            captured[rel_pattern] = file_captured
    return captured


def _synchronized_ledger_entries(
    workspace_root: Path,
    roots: Mapping[str, str],
    synchronized: Sequence[ResourcePath],
) -> dict[str, _Entry]:
    """Collect workspace ``events.jsonl`` files under synchronized project prefixes."""
    found: dict[str, _Entry] = {}
    for path in synchronized:
        if path.root != "project" or path.segments[-1] != "**":
            continue
        directory_rel = path.pattern.removesuffix("/**")
        events_rel = f"{directory_rel}/events.jsonl" if directory_rel else "events.jsonl"
        physical = _physical_for(roots, ResourcePath.parse(f"project:{events_rel}"))
        entry = _entry_at(workspace_root, physical)
        if entry is not None:
            found[physical] = entry
        if directory_rel in {"qa/changes", "qa/archive"}:
            directory = workspace_root / _physical_for(
                roots,
                ResourcePath.parse(f"project:{directory_rel}"),
            )
            if not directory.is_dir():
                continue
            for change_dir in sorted(item for item in directory.iterdir() if item.is_dir()):
                for suffix in (Path("events.jsonl"), Path("issues/events.jsonl")):
                    ledger = change_dir / suffix
                    ledger_rel = ledger.relative_to(workspace_root).as_posix()
                    ledger_entry = _entry_at(workspace_root, ledger_rel)
                    if ledger_entry is not None:
                        found[ledger_rel] = ledger_entry
    return found


def _entry_and_bytes_at(project_root: Path, rel: str) -> tuple[_Entry, bytes] | None:
    root = project_root.resolve()
    target = root / rel
    if not _is_within(target.parent.resolve(), root):
        raise WorkspaceError(f"targeted path escapes project root: {rel}")
    if target.is_symlink():
        link_target = os.readlink(target)
        if not _is_within((target.parent / link_target).resolve(), project_root):
            raise WorkspaceError(f"targeted symlink escapes project root: {rel}")
        data = link_target.encode("utf-8")
        return _Entry(kind="symlink", sha256=hashlib.sha256(data).hexdigest()), data
    if not target.exists():
        return None
    if not target.is_file():
        raise WorkspaceError(f"targeted write-set path is not a file: {rel}")
    data = target.read_bytes()
    executable = bool(target.stat(follow_symlinks=False).st_mode & 0o100)
    return (
        _Entry(kind="file", sha256=hashlib.sha256(data).hexdigest(), executable=executable),
        data,
    )


def _entry_at(project_root: Path, rel: str) -> _Entry | None:
    captured = _entry_and_bytes_at(project_root, rel)
    return captured[0] if captured is not None else None


# ---------------------------------------------------------------------------
# write-set 模型


class WriteEntry(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")
    logical_path: str
    operation: Literal["add", "modify", "delete"]
    before_sha256: str | None
    after_sha256: str | None
    blob_sha256: str | None
    executable: bool = False


class WriteSet(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")
    write_set_id: str
    task_id: str
    base_tree_id: str
    entries: tuple[WriteEntry, ...]
    outputs_sha256: dict[str, str]
    synchronized_paths: tuple[str, ...] = ()
    project_exclusive_tokens: tuple[str, ...] = ()


# ---------------------------------------------------------------------------
# TreeStore：内容寻址对象库 + tree capture/materialize + write-set freeze/merge


class TreeStore:
    """change dir 下的内容寻址对象库；coordinator 独占写入。"""

    def __init__(self, change_dir: Path) -> None:
        self._change_dir = change_dir
        self._objects = change_dir / _OBJECTS_RELPATH

    # ---- 对象库原语 ----

    def _object_path(self, digest: str) -> Path:
        _assert_digest(digest)
        return self._objects / digest[:2] / digest

    def _write_object(self, digest: str, data: bytes) -> None:
        path = self._object_path(digest)
        path.parent.mkdir(parents=True, exist_ok=True)
        try:
            with open(path, "xb") as handle:
                handle.write(data)
                handle.flush()
                os.fsync(handle.fileno())
        except FileExistsError:
            # 已存在的对象必须先验证 hash 再复用：篡改/冲突不允许静默通过。
            self._read_object(digest)

    def _read_object(self, digest: str) -> bytes:
        path = self._object_path(digest)
        try:
            data = path.read_bytes()
        except OSError as exc:
            raise WorkspaceError(f"object missing from store: {digest}") from exc
        if hashlib.sha256(data).hexdigest() != digest:
            raise WorkspaceError(f"object store bytes tampered: {digest}")
        return data

    def read_object(self, digest: str) -> bytes:
        """Read content-addressed blob bytes (public wrapper)."""
        return self._read_object(digest)

    # ---- tree capture / materialize ----

    def _roots(self, project_root: Path, repo_root: Path | None) -> dict[str, str]:
        def prefix(path: Path) -> str:
            resolved = path.resolve()
            if resolved == project_root:
                return "."
            try:
                return resolved.relative_to(project_root).as_posix()
            except ValueError as exc:
                raise WorkspaceError(f"logical root escapes project root: {path}") from exc

        return {
            "change": prefix(self._change_dir),
            "project": ".",
            "repo": prefix(repo_root) if repo_root is not None else ".",
        }

    def capture(self, project_root: Path, *, repo_root: Path | None = None) -> str:
        """把 project root 固化成内容寻址 tree manifest，返回 tree id（确定性）。"""
        project_root = project_root.resolve()
        if not project_root.is_dir():
            raise WorkspaceError(f"project root is not a directory: {project_root}")
        roots = self._roots(project_root, repo_root)
        entries = _walk(project_root, keep_change_dir=self._change_dir)
        for rel, entry in entries.items():
            if entry.kind == "file":
                data = (project_root / rel).read_bytes()
                if hashlib.sha256(data).hexdigest() != entry.sha256:
                    raise WorkspaceError(f"path changed during capture: {rel}")
            else:
                data = os.readlink(project_root / rel).encode("utf-8")
            self._write_object(entry.sha256, data)
        raw = _canonical_json(_tree_payload(roots, entries))
        tree_id = hashlib.sha256(raw).hexdigest()
        self._write_object(tree_id, raw)
        return tree_id

    def _load_tree(self, tree_id: str) -> _TreeManifest:
        return _parse_tree(self._read_object(tree_id))

    def _read_tree_bytes(
        self,
        manifest: _TreeManifest,
        rel: str,
    ) -> bytes:
        current = rel
        visited_states: set[str] = set()
        hops = 0
        while True:
            if current in visited_states:
                raise WorkspaceError(f"tree symlink cycle while resolving: {current}")
            visited_states.add(current)
            parts = PurePosixPath(current).parts
            followed = False
            for index in range(1, len(parts) + 1):
                prefix = PurePosixPath(*parts[:index]).as_posix()
                entry = manifest.entries.get(prefix)
                if entry is None:
                    continue
                data = self._read_object(entry.sha256)
                if entry.kind == "file":
                    if index != len(parts):
                        raise NotADirectoryError(current)
                    return data
                if hops >= _MAX_TREE_SYMLINK_HOPS:
                    raise WorkspaceError(f"too many symlink hops while resolving tree path: {rel}")
                try:
                    target = data.decode("utf-8")
                except UnicodeDecodeError as exc:
                    raise WorkspaceError(f"tree symlink target is not UTF-8: {prefix}") from exc
                hops += 1
                resolved = _resolve_tree_symlink(prefix, target)
                current = PurePosixPath(resolved, *parts[index:]).as_posix()
                followed = True
                break
            if followed:
                continue
            directory_prefix = f"{current}/"
            if current == "." or any(path.startswith(directory_prefix) for path in manifest.entries):
                raise IsADirectoryError(current)
            raise FileNotFoundError(current)

    def read_bytes(self, tree_id: str, logical_path: str) -> bytes:
        """Read hash-verified file bytes from a committed tree, following safe symlinks."""
        logical = ResourcePath.parse(logical_path)
        manifest = self._load_tree(tree_id)
        rel = _physical_for(manifest.roots, logical)
        try:
            return self._read_tree_bytes(manifest, rel)
        except FileNotFoundError as exc:
            raise FileNotFoundError(logical_path) from exc

    def read_json(self, tree_id: str, logical_path: str) -> ResolvedArtifact:
        """Read a JSON artifact from a committed tree by logical path (change:/project:/repo:)."""
        data = self.read_bytes(tree_id, logical_path)
        try:
            value = json.loads(data.decode("utf-8"))
        except (UnicodeDecodeError, json.JSONDecodeError) as exc:
            raise ValueError(f"artifact is not valid JSON: {logical_path}") from exc
        return ResolvedArtifact(
            value=value,
            reads_sha256={logical_path: hashlib.sha256(data).hexdigest()},
        )

    def filter_tree(
        self,
        tree_id: str,
        claims: ResourceClaims,
        *,
        declared_reads_only: bool = False,
        skill_name: str | None = None,
    ) -> str:
        """Return the task's materializable read view without changing its merge base.

        When task claims name concrete ``project:qa/retro/<id>/...`` paths,
        other ``qa/retro/<sibling>/`` entries are dropped from the materialized
        workspace. With ``declared_reads_only``, every entry outside declared
        contract/node reads is removed as well; ``skills/<skill_name>/**`` remains
        visible so the selected agent can load its own bundle. The freeze/merge
        ``base_tree_id`` stays the full overlay tree — callers must not rebind it
        to this filtered id.
        """
        manifest = self._load_tree(tree_id)
        claimed_retro_ids = _claimed_retro_run_ids(claims)
        if not claimed_retro_ids and not declared_reads_only:
            return tree_id
        entries = {}
        for rel, entry in manifest.entries.items():
            if _is_omitted_retro_sibling(manifest.roots, rel, claimed_retro_ids):
                continue
            if declared_reads_only and not _entry_visible_to_declared_skill(
                manifest.roots,
                rel,
                claims,
                skill_name,
            ):
                continue
            entries[rel] = entry
        if entries == manifest.entries:
            return tree_id
        raw = _canonical_json(_tree_payload(manifest.roots, entries))
        filtered_id = hashlib.sha256(raw).hexdigest()
        self._write_object(filtered_id, raw)
        return filtered_id

    def materialize(self, tree_id: str, dest: Path) -> None:
        """把 tree 物化到空目录 ``dest``，并写入 ``.graph-runtime/tree.json`` 元数据。"""
        manifest = self._load_tree(tree_id)
        dest = dest.resolve()
        dest.mkdir(parents=True, exist_ok=True)
        for prefix in manifest.roots.values():
            (dest / prefix).mkdir(parents=True, exist_ok=True)
        for rel, entry in sorted(manifest.entries.items()):
            target = (dest / rel).resolve()
            if not _is_within(target, dest):
                raise WorkspaceError(f"tree entry escapes materialization root: {rel}")
            data = self._read_object(entry.sha256)
            if entry.kind == "symlink":
                link_target = data.decode("utf-8")
                if not _is_within((target.parent / link_target).resolve(), dest):
                    raise WorkspaceError(f"tree symlink escapes materialization root: {rel}")
                target.parent.mkdir(parents=True, exist_ok=True)
                os.symlink(link_target, target)
            else:
                _install_file(target, data, entry.executable)
        manifest_path = dest / _TREE_MANIFEST_RELPATH
        manifest_path.parent.mkdir(parents=True, exist_ok=True)
        manifest_path.write_bytes(manifest.raw)

    # ---- write-set freeze / load ----

    def freeze_write_set(
        self,
        workspace: "TaskWorkspace",
        *,
        claims: ResourceClaims,
        outputs: tuple[str, ...] = (),
    ) -> WriteSet:
        """独立计算 workspace 与 base tree 的完整 diff，校验授权与 outputs 后固化。

        每个实际变化路径必须被 ``authorization_writes`` 覆盖（fail closed）；
        变化的 symlink 一律拒绝；声明的 output 必须是存在的具体文件。
        """
        base = self._load_tree(workspace.base_tree_id)
        materialized = (
            self._load_tree(workspace.materialized_tree_id)
            if workspace.materialized_tree_id is not None
            else base
        )
        current = _walk(workspace.root)
        # Synchronized project ledgers keep events.jsonl out of ordinary capture
        # but must still enter the write-set for targeted publication.
        if claims.synchronized:
            for rel, entry in _synchronized_ledger_entries(
                workspace.root, base.roots, claims.synchronized
            ).items():
                current[rel] = entry
        claimed_retro_ids = _claimed_retro_run_ids(claims)
        entries: list[WriteEntry] = []
        for rel in sorted(set(base.entries) | set(current)):
            if _is_excluded_rel(rel) and not _is_synchronized_ledger_rel(
                base.roots, rel, claims.synchronized
            ):
                # Runtime side-effects may still sit in older base trees; never
                # promote them into write-sets once they are capture-excluded.
                continue
            before = base.entries.get(rel)
            after = current.get(rel)
            if before == after:
                continue
            # Sibling Retro dirs were intentionally not materialized; absence is
            # not a delete against the full freeze/merge base tree.
            if (
                after is None
                and before is not None
                and (
                    rel not in materialized.entries
                    or _is_omitted_retro_sibling(base.roots, rel, claimed_retro_ids)
                )
            ):
                continue
            if (before is not None and before.kind == "symlink") or (
                after is not None and after.kind == "symlink"
            ):
                raise WorkspaceError(f"changed symlink rejected: {rel}")
            logical = _canonical_logical(base.roots, rel)
            logical_path = ResourcePath.parse(logical)
            if (
                claims.synchronized
                and logical_path.root == "project"
                and not any(path_covers(prefix, logical_path) for prefix in claims.synchronized)
                and not _is_declared_aliased_repo_test_write(base.roots, rel, claims)
            ):
                raise WorkspaceError(f"synchronized write outside declared prefixes: {logical}")
            if not _is_authorized(base.roots, rel, claims):
                raise WorkspaceError(f"forbidden write outside authorization_writes: {logical}")
            if after is None:
                entries.append(
                    WriteEntry(
                        logical_path=logical,
                        operation="delete",
                        before_sha256=before.sha256 if before else None,
                        after_sha256=None,
                        blob_sha256=None,
                    )
                )
                continue
            data = (workspace.root / rel).read_bytes()
            if hashlib.sha256(data).hexdigest() != after.sha256:
                raise WorkspaceError(f"path changed during freeze: {rel}")
            self._write_object(after.sha256, data)
            entries.append(
                WriteEntry(
                    logical_path=logical,
                    operation="add" if before is None else "modify",
                    before_sha256=before.sha256 if before else None,
                    after_sha256=after.sha256,
                    blob_sha256=after.sha256,
                    executable=after.executable,
                )
            )
        outputs_sha256 = self._freeze_outputs(base.roots, current, outputs, workspace=workspace)
        payload: dict[str, object] = {
            "base_tree_id": workspace.base_tree_id,
            "entries": [entry.model_dump(mode="json") for entry in entries],
            "kind": "write_set",
            "outputs_sha256": outputs_sha256,
            "project_exclusive_tokens": sorted(
                token for token in claims.exclusive if claims.synchronized and token.startswith("project:")
            ),
            "synchronized_paths": sorted(f"{path.root}:{path.pattern}" for path in claims.synchronized),
            "task_id": workspace.task_id,
            "version": 1,
        }
        raw = _canonical_json(payload)
        write_set_id = hashlib.sha256(raw).hexdigest()
        self._write_object(write_set_id, raw)
        return WriteSet(
            write_set_id=write_set_id,
            task_id=workspace.task_id,
            base_tree_id=workspace.base_tree_id,
            entries=tuple(entries),
            outputs_sha256=outputs_sha256,
            synchronized_paths=tuple(sorted(f"{path.root}:{path.pattern}" for path in claims.synchronized)),
            project_exclusive_tokens=tuple(
                sorted(
                    token
                    for token in claims.exclusive
                    if claims.synchronized and token.startswith("project:")
                )
            ),
        )

    def _freeze_outputs(
        self,
        roots: Mapping[str, str],
        current: Mapping[str, _Entry],
        outputs: tuple[str, ...],
        *,
        workspace: "TaskWorkspace | None" = None,
    ) -> dict[str, str]:
        frozen: dict[str, str] = {}
        for declared in outputs:
            logical = ResourcePath.parse(declared)
            if logical.root == "global" or any("*" in segment for segment in logical.segments):
                raise WorkspaceError(f"declared output must be a concrete file path: {declared}")
            rel = _physical_for(roots, logical)
            entry = current.get(rel)
            if entry is not None and entry.kind == "file":
                frozen[declared] = entry.sha256
                continue
            # Directory outputs (schema trailing slash, e.g. change:cases/) — require
            # at least one captured file under the prefix and hash the closure.
            dir_declared = declared.rstrip().endswith("/")
            prefix = f"{rel}/"
            under = {
                path: item
                for path, item in current.items()
                if path.startswith(prefix) and item.kind == "file"
            }
            if dir_declared or under:
                if not under:
                    raise WorkspaceError(f"declared output directory empty or missing: {declared}")
                canonical = "\n".join(f"{path}:{item.sha256}" for path, item in sorted(under.items()))
                frozen[declared] = hashlib.sha256(canonical.encode()).hexdigest()
                continue
            # coordinator projection files are excluded from tree walk but may be
            # declared node outputs (e.g. change:workflow-state.yaml).
            basename = logical.segments[-1] if logical.segments else ""
            if basename in _EXCLUDED_FILES and workspace is not None and (workspace.root / rel).is_file():
                data = (workspace.root / rel).read_bytes()
                frozen[declared] = hashlib.sha256(data).hexdigest()
                continue
            raise WorkspaceError(f"declared output missing or not a file: {declared}")
        return frozen

    def load_write_set(self, write_set_id: str) -> WriteSet:
        """按内容地址读回 write-set；字节篡改在 hash 校验处 fail closed。"""
        payload = json.loads(self._read_object(write_set_id))
        if not isinstance(payload, dict) or payload.get("kind") != "write_set":
            raise WorkspaceError(f"invalid write-set manifest: {write_set_id}")
        fields = {k: v for k, v in payload.items() if k not in ("kind", "version")}
        try:
            return WriteSet.model_validate({**fields, "write_set_id": write_set_id})
        except ValueError as exc:
            raise WorkspaceError(f"invalid write-set manifest {write_set_id}: {exc}") from exc

    # ---- Update：确定性合并 + canonical 幂等物化 ----

    def merge_write_sets(self, write_sets: Iterable[WriteSet]) -> str:
        """按 structural task ID 排序合并同 wave write-sets，返回 target tree id。

        sibling 实际触碰同一逻辑路径、entry 的 before_sha256 与 base tree 不一致、
        或 write-sets 不共享同一 base，一律 fail closed。
        """
        ordered = sorted(write_sets, key=lambda write_set: write_set.task_id)
        if not ordered:
            raise WorkspaceError("no write-sets to merge")
        base_ids = {write_set.base_tree_id for write_set in ordered}
        if len(base_ids) != 1:
            raise WorkspaceError("write-sets do not share one base tree")
        base = self._load_tree(ordered[0].base_tree_id)
        entries = dict(base.entries)
        touched: dict[str, str] = {}
        for write_set in ordered:
            for entry in write_set.entries:
                previous = touched.get(entry.logical_path)
                if previous is not None:
                    raise WorkspaceError(
                        f"overlapping sibling write-sets at {entry.logical_path}: "
                        f"{previous} vs {write_set.task_id}"
                    )
                touched[entry.logical_path] = write_set.task_id
                logical = ResourcePath.parse(entry.logical_path)
                rel = _physical_for(base.roots, logical)
                current = entries.get(rel)
                current_sha = current.sha256 if current else None
                if entry.before_sha256 != current_sha:
                    raise WorkspaceError(
                        f"write-set entry {entry.logical_path} before_sha256 disagrees with base tree"
                    )
                if entry.operation == "delete":
                    del entries[rel]
                else:
                    if entry.after_sha256 is None:
                        raise WorkspaceError(f"write-set entry missing after_sha256: {entry.logical_path}")
                    entries[rel] = _Entry(kind="file", sha256=entry.after_sha256, executable=entry.executable)
        raw = _canonical_json(_tree_payload(base.roots, entries))
        target_tree_id = hashlib.sha256(raw).hexdigest()
        self._write_object(target_tree_id, raw)
        return target_tree_id

    def overlay_synchronized_paths_many(
        self,
        tree_ids: Sequence[str],
        project_root: Path,
        paths: Sequence[ResourcePath],
    ) -> tuple[str, ...]:
        """Replace declared synchronized paths in every tree from one live capture."""
        synchronized = _validated_synchronized_paths(paths)
        if not synchronized:
            return tuple(tree_ids)
        project_root = project_root.resolve()
        if not project_root.is_dir():
            raise WorkspaceError(f"project root is not a directory: {project_root}")
        if not tree_ids:
            return tuple(tree_ids)
        trees = [self._load_tree(tree_id) for tree_id in tree_ids]
        roots = trees[0].roots
        for tree in trees[1:]:
            if tree.roots != roots:
                raise WorkspaceError("supplied trees must share the same logical-root mapping")
        live = _capture_synchronized_entries(
            project_root,
            roots,
            synchronized,
            active_change_dir=self._change_dir,
        )
        live_entries = {rel: entry for rel, (entry, _data) in live.items()}
        for _rel, (entry, data) in live.items():
            self._write_object(entry.sha256, data)
        overlay_ids: list[str] = []
        for base in trees:
            entries = dict(base.entries)
            for rel in sorted(set(base.entries) | set(live_entries)):
                if not _matches_synchronized_path(base.roots, rel, synchronized):
                    continue
                current = live_entries.get(rel)
                if current is None:
                    entries.pop(rel, None)
                    continue
                entries[rel] = current
            raw = _canonical_json(_tree_payload(base.roots, entries))
            overlay_tree_id = hashlib.sha256(raw).hexdigest()
            self._write_object(overlay_tree_id, raw)
            overlay_ids.append(overlay_tree_id)
        return tuple(overlay_ids)

    def overlay_synchronized_paths(
        self,
        base_tree_id: str,
        project_root: Path,
        paths: Sequence[ResourcePath],
    ) -> str:
        """Replace only declared synchronized paths in ``base_tree_id`` from the live root."""
        (overlay_tree_id,) = self.overlay_synchronized_paths_many(
            (base_tree_id,),
            project_root,
            paths,
        )
        return overlay_tree_id

    def apply_write_sets_to_synchronized_paths(
        self,
        project_root: Path,
        write_sets: Iterable[WriteSet],
        paths: Sequence[ResourcePath],
    ) -> None:
        """Apply only write-set entries, validating against their live-overlay base tree.

        Synchronized entries therefore compare with the locked live state captured by
        ``overlay_synchronized_paths``; every other entry compares with the invocation
        snapshot retained in that same overlay tree. Unrelated canonical paths are never
        walked or materialized.
        """
        synchronized = _validated_synchronized_paths(paths)
        if not synchronized:
            raise WorkspaceError("targeted synchronized apply requires synchronized paths")
        ordered = sorted(write_sets, key=lambda write_set: write_set.task_id)
        if not ordered:
            return
        base_ids = {write_set.base_tree_id for write_set in ordered}
        if len(base_ids) != 1:
            raise WorkspaceError("write-sets do not share one synchronized overlay base tree")
        base = self._load_tree(ordered[0].base_tree_id)
        project_root = project_root.resolve()
        if not project_root.is_dir():
            raise WorkspaceError(f"project root is not a directory: {project_root}")

        touched: dict[str, str] = {}
        writes: list[tuple[str, _Entry]] = []
        deletes: list[str] = []
        for write_set in ordered:
            for entry in write_set.entries:
                previous = touched.get(entry.logical_path)
                if previous is not None:
                    raise WorkspaceError(
                        f"overlapping sibling write-sets at {entry.logical_path}: "
                        f"{previous} vs {write_set.task_id}"
                    )
                touched[entry.logical_path] = write_set.task_id
                logical = ResourcePath.parse(entry.logical_path)
                if any("*" in segment for segment in logical.segments):
                    raise WorkspaceError(f"write-set entry must be a concrete path: {entry.logical_path}")
                rel = _physical_for(base.roots, logical)
                before = base.entries.get(rel)
                before_sha = before.sha256 if before is not None else None
                if entry.before_sha256 != before_sha:
                    scope = (
                        "synchronized live overlay"
                        if logical.root == "project"
                        and any(path_covers(prefix, logical) for prefix in synchronized)
                        else "invocation base"
                    )
                    raise WorkspaceError(
                        f"write-set entry {entry.logical_path} before_sha256 disagrees with {scope}"
                    )
                if entry.operation == "delete":
                    if entry.after_sha256 is not None or entry.blob_sha256 is not None:
                        raise WorkspaceError(
                            f"delete write-set entry carries after content: {entry.logical_path}"
                        )
                    wanted = None
                else:
                    if entry.after_sha256 is None or entry.blob_sha256 != entry.after_sha256:
                        raise WorkspaceError(
                            f"write-set entry missing matching content hash: {entry.logical_path}"
                        )
                    self._read_object(entry.after_sha256)
                    wanted = _Entry(
                        kind="file",
                        sha256=entry.after_sha256,
                        executable=entry.executable,
                    )
                actual = _entry_at(project_root, rel)
                if actual == wanted:
                    continue
                if _same_file_content(actual, wanted):
                    assert wanted is not None
                    writes.append((rel, wanted))
                    continue
                if actual != before:
                    raise WorkspaceError(f"canonical workspace drift at targeted path {entry.logical_path}")
                if wanted is None:
                    deletes.append(rel)
                else:
                    writes.append((rel, wanted))

        for rel, wanted in sorted(writes):
            _install_file(project_root / rel, self._read_object(wanted.sha256), wanted.executable)
        for rel in sorted(deletes):
            victim = project_root / rel
            victim.unlink(missing_ok=True)
            _prune_empty_parents(victim, project_root)

    def apply_tree(self, project_root: Path, target_tree_id: str, *, base_tree_id: str) -> None:
        """把 canonical root 从 base tree 幂等推进到 target tree。

        先整体验证：任何落在 ``{base, target}`` 之外的状态都是 canonical 漂移，
        fail closed 且不触碰磁盘。之后写 entry 用 temp-file + ``os.replace``、
        delete 最后执行；partial apply 后重放同一 target 必收敛。
        """
        project_root = project_root.resolve()
        base = self._load_tree(base_tree_id)
        target = self._load_tree(target_tree_id)
        current = _walk(project_root, keep_change_dir=self._change_dir)
        # 本 change 目录（qa/changes/<id>/）是 runtime 独占产出区：落在其中的
        # untracked 路径通常是 agent 把声明产物用绝对路径直写进 canonical（而非
        # 其 task 沙箱）留下的越界残留。此类残留由重跑节点重新生成、只经受控
        # write-set 提升，故 resume 修复时清理而非以 canonical drift 阻断；change
        # 目录之外的 untracked 路径仍是真实源码漂移，一律 fail closed。
        resolved_change = self._change_dir.resolve()
        change_prefix: str | None = None
        if _is_within(resolved_change, project_root):
            change_prefix = resolved_change.relative_to(project_root).as_posix()
        writes: list[tuple[str, _Entry]] = []
        deletes: list[str] = []
        change_dir_strays: list[str] = []
        for rel in sorted(set(base.entries) | set(target.entries)):
            if _is_excluded_rel(rel):
                continue
            before = base.entries.get(rel)
            wanted = target.entries.get(rel)
            actual = current.get(rel)
            if before == wanted:
                if actual != before:
                    # ``_walk(..., keep_change_dir=...)`` intentionally omits
                    # sibling Change trees. A synchronized read snapshot may
                    # carry those immutable entries through the committed tree;
                    # unchanged siblings are not canonical drift merely because
                    # the ordinary walker does not revisit them.
                    if (
                        actual is None
                        and change_prefix is not None
                        and rel.startswith("qa/changes/")
                        and rel != change_prefix
                        and not rel.startswith(f"{change_prefix}/")
                    ):
                        continue
                    if before is not None and actual is None:
                        writes.append((rel, before))
                        continue
                    if before is not None and _path_matches_entry(project_root / rel, before):
                        continue
                    raise WorkspaceError(f"canonical workspace drift at {rel}")
                continue
            if actual == wanted:
                continue  # 已物化（重放/幂等）
            if _same_file_content(actual, wanted):
                assert wanted is not None
                writes.append((rel, wanted))
                continue
            if actual != before:
                if wanted is not None and _path_matches_entry(project_root / rel, wanted):
                    continue
                raise WorkspaceError(f"canonical workspace drift at {rel}")
            if wanted is None:
                deletes.append(rel)
            else:
                if wanted.kind != "file":
                    raise WorkspaceError(f"cannot materialize non-file entry: {rel}")
                writes.append((rel, wanted))
        for rel in sorted(set(current) - set(base.entries) - set(target.entries)):
            if _is_excluded_rel(rel):
                continue
            if change_prefix is not None and (rel == change_prefix or rel.startswith(f"{change_prefix}/")):
                change_dir_strays.append(rel)
                continue
            raise WorkspaceError(f"canonical workspace drift: untracked path {rel}")

        for rel, entry in writes:
            _install_file(project_root / rel, self._read_object(entry.sha256), entry.executable)
        for rel in deletes + change_dir_strays:
            victim = project_root / rel
            victim.unlink(missing_ok=True)
            _prune_empty_parents(victim, project_root)


# ---------------------------------------------------------------------------
# 逻辑路径解析


def _resolutions(roots: Mapping[str, str], rel: str) -> list[tuple[str, str]]:
    """物理相对路径 → 所有可能的 ``(逻辑 root, root 内路径)``（root 可能互为别名）。"""
    found: list[tuple[str, str]] = []
    for name, prefix in roots.items():
        if prefix == ".":
            found.append((name, rel))
        elif rel.startswith(f"{prefix}/"):
            found.append((name, rel[len(prefix) + 1 :]))
    return found


def _canonical_logical(roots: Mapping[str, str], rel: str) -> str:
    """确定性 canonical 逻辑路径：最长前缀优先，并列按 root 名字典序。"""
    found = _resolutions(roots, rel)
    if not found:
        raise WorkspaceError(f"path resolves outside every logical root: {rel}")
    name, logical = min(found, key=lambda item: (-len(roots[item[0]]), item[0]))
    return f"{name}:{logical}"


def _is_authorized(roots: Mapping[str, str], rel: str, claims: ResourceClaims) -> bool:
    for name, logical in _resolutions(roots, rel):
        claim = ResourcePath.parse(f"{name}:{logical}")
        if any(path_covers(authorization, claim) for authorization in claims.authorization_writes):
            return True
    return False


def _is_declared_aliased_repo_test_write(
    roots: Mapping[str, str],
    rel: str,
    claims: ResourceClaims,
) -> bool:
    """Return whether an aliased physical path is an authorized repo test write.

    ``project`` and ``repo`` may intentionally point at the same SUT root.  The
    canonical logical name is then ``project`` by lexical tie-break, but a graph
    footprint can still legitimately own the path through a narrower
    ``repo:tests/**`` claim.  This exception is deliberately limited to that
    execution-contract namespace: a broad ``repo:**`` claim must not turn into
    a general bypass of synchronized project scope.  Require both a write claim
    and authorization so a broad read or authorization alone is insufficient.
    """
    if roots.get("repo") != roots.get("project"):
        return False
    for name, logical in _resolutions(roots, rel):
        if name != "repo":
            continue
        path = ResourcePath.parse(f"{name}:{logical}")
        if not path.segments or path.segments[0] != "tests":
            continue
        if any(path_covers(write, path) for write in claims.writes) and any(
            path_covers(authorization, path) for authorization in claims.authorization_writes
        ):
            return True
    return False


def _entry_covered_by_claims(
    roots: Mapping[str, str],
    rel: str,
    claims: ResourceClaims,
) -> bool:
    """True when a physical tree entry is in the task's declared read/write scope."""
    bounds = (*claims.reads, *claims.writes, *claims.authorization_writes)
    if not bounds:
        return True
    for name, logical in _resolutions(roots, rel):
        path = ResourcePath.parse(f"{name}:{logical}")
        if any(path_covers(bound, path) for bound in bounds):
            return True
    return False


def _entry_visible_to_declared_skill(
    roots: Mapping[str, str],
    rel: str,
    claims: ResourceClaims,
    skill_name: str | None,
) -> bool:
    """Keep only declared reads plus the target skill's instruction bundle."""
    support_prefixes = (f"skills/{skill_name}/",) if skill_name else ()
    for name, logical in _resolutions(roots, rel):
        path = ResourcePath.parse(f"{name}:{logical}")
        if any(path_covers(read, path) for read in claims.reads):
            return True
        if name == "project" and any(logical.startswith(prefix) for prefix in support_prefixes):
            return True
    return False


def _claimed_retro_run_ids(claims: ResourceClaims) -> frozenset[str]:
    """Concrete ``qa/retro/<id>`` run ids pinned by task read/write claims."""
    ids: set[str] = set()
    for bound in (*claims.reads, *claims.writes, *claims.authorization_writes):
        if bound.root != "project":
            continue
        segments = bound.segments
        if (
            len(segments) >= 3
            and segments[0] == "qa"
            and segments[1] == "retro"
            and segments[2] not in ("*", "**")
        ):
            ids.add(segments[2])
    return frozenset(ids)


def _is_omitted_retro_sibling(
    roots: Mapping[str, str],
    rel: str,
    claimed_retro_ids: frozenset[str],
) -> bool:
    """True for ``qa/retro/<other>/...`` entries when claims pin specific run ids."""
    if not claimed_retro_ids:
        return False
    try:
        logical = ResourcePath.parse(_canonical_logical(roots, rel))
    except WorkspaceError:
        return False
    if logical.root != "project":
        return False
    segments = logical.segments
    if len(segments) < 3 or segments[0] != "qa" or segments[1] != "retro":
        return False
    run_id = segments[2]
    return run_id not in claimed_retro_ids and run_id not in ("*", "**")


def _physical_for(roots: Mapping[str, str], logical: ResourcePath) -> str:
    prefix = roots.get(logical.root)
    if prefix is None:
        raise WorkspaceError(f"unknown logical root: {logical.root}")
    prefix = _assert_safe_prefix(prefix)
    return logical.pattern if prefix == "." else f"{prefix}/{logical.pattern}"


# ---------------------------------------------------------------------------
# TaskWorkspace 与后端


@dataclass(frozen=True)
class TaskWorkspace:
    task_id: str
    root: Path
    project_root: Path
    repo_root: Path
    change_dir: Path
    base_tree_id: str
    materialized_tree_id: str | None = None

    def cleanup(self) -> None:
        shutil.rmtree(self.root, ignore_errors=True)

    @classmethod
    def from_materialized_root(
        cls,
        task_id: str,
        root: Path,
        base_tree_id: str,
        materialized_tree_id: str | None = None,
    ) -> "TaskWorkspace":
        """从物化 root 的 tree manifest 解析逻辑 project/repo/change root。

        manifest 缺失、root 未声明、root 目录不存在或解析到物化 root 之外，
        一律拒绝。
        """
        manifest_path = root / _TREE_MANIFEST_RELPATH
        try:
            payload = json.loads(manifest_path.read_bytes())
        except (OSError, json.JSONDecodeError) as exc:
            raise WorkspaceError(f"materialized root lacks a tree manifest: {root}") from exc
        raw_roots = payload.get("roots") if isinstance(payload, dict) else None
        if not isinstance(raw_roots, dict):
            raise WorkspaceError(f"materialized tree manifest lacks roots: {root}")
        resolved_root = root.resolve()

        def resolve_logical(name: str) -> Path:
            prefix = raw_roots.get(name)
            if not isinstance(prefix, str):
                raise WorkspaceError(f"tree manifest missing logical root '{name}': {root}")
            candidate = (resolved_root / _assert_safe_prefix(prefix)).resolve()
            if not _is_within(candidate, resolved_root):
                raise WorkspaceError(f"logical root '{name}' escapes materialized root: {root}")
            if not candidate.is_dir():
                raise WorkspaceError(f"logical root '{name}' missing in materialized root: {root}")
            return candidate

        return cls(
            task_id=task_id,
            root=root,
            project_root=resolve_logical("project"),
            repo_root=resolve_logical("repo"),
            change_dir=resolve_logical("change"),
            base_tree_id=base_tree_id,
            materialized_tree_id=materialized_tree_id,
        )


def _assert_safe_task_id(task_id: str) -> None:
    if not task_id or task_id in (".", "..") or "/" in task_id or "\\" in task_id:
        raise WorkspaceError(f"unsafe task_id for workspace directory: {task_id!r}")


class WorkspaceBackend:
    def __init__(self, change_dir: Path) -> None:
        self._tasks_root = change_dir / _TASKS_RELPATH

    def create(
        self,
        *,
        task_id: str,
        base_tree_id: str,
        store: TreeStore,
        side_effect_free: bool = False,
        claims: ResourceClaims | None = None,
        declared_reads_only: bool = False,
        skill_name: str | None = None,
        initialize_git: bool = True,
    ) -> TaskWorkspace:
        _assert_safe_task_id(task_id)
        root = self._tasks_root / task_id
        if root.exists():
            shutil.rmtree(root)
        root.mkdir(parents=True)
        # Materialize a sibling-omitted view when claims pin a Retro run, but
        # keep freeze/merge base_tree_id on the full overlay/invocation tree.
        materialize_tree = (
            store.filter_tree(
                base_tree_id,
                claims,
                declared_reads_only=declared_reads_only,
                skill_name=skill_name,
            )
            if claims is not None
            else base_tree_id
        )
        store.materialize(materialize_tree, root)
        if initialize_git:
            self._init_convenience_git(root, side_effect_free=side_effect_free)
        return TaskWorkspace.from_materialized_root(
            task_id,
            root,
            base_tree_id,
            materialized_tree_id=materialize_tree,
        )

    @staticmethod
    def _init_convenience_git(root: Path, *, side_effect_free: bool) -> None:
        """task 本地 git 便利索引：给 phase agent ``git status``/``git diff`` 基线。

        不共享 canonical 仓库元数据。git 不存在时跳过；初始化失败对 agent
        target 是 contract error，仅显式 side-effect-free 的 builtin target
        可以忽略。
        """
        git = shutil.which("git")
        if git is None:
            return
        try:
            subprocess.run(
                [git, "init", "-q"], cwd=root, check=True, capture_output=True, timeout=_GIT_TIMEOUT_S
            )
            subprocess.run(
                [git, "add", "-f", "-A"],
                cwd=root,
                check=True,
                capture_output=True,
                timeout=_GIT_TIMEOUT_S,
            )
        except (OSError, subprocess.SubprocessError) as exc:
            if side_effect_free:
                return
            raise WorkspaceError(f"task-local git convenience index failed: {exc}") from exc


__all__ = [
    "TaskWorkspace",
    "TreeStore",
    "WorkspaceBackend",
    "WorkspaceError",
    "WriteEntry",
    "WriteSet",
]
