from __future__ import annotations

import base64
from collections.abc import Mapping
from dataclasses import dataclass
import hashlib
import re
from pathlib import Path, PurePosixPath
from typing import cast
from zipfile import ZIP_DEFLATED, ZipFile, ZipInfo

import yaml

from graph_engine.canonical import JSONValue, canonical_digest, canonical_json_bytes

from assurance_product.models import (
    ENGINE_API,
    PLUGIN_ID,
    PLUGIN_VERSION,
    PREPARE_IDS,
    BuiltDeploymentWheel,
    DeploymentBindingsV1,
    adapter_secret_handles,
    alias_ids_for_prepare,
    expected_finalize_ids,
)

_WHEEL_EPOCH = (1980, 1, 1, 0, 0, 0)
_FILE_MODE = 0o644
_CAPABILITY_DEPENDENCIES: tuple[tuple[str, str], ...] = (
    ("assurance.intake", "==0.1.0"),
    ("assurance.generation", "==0.1.0"),
    ("assurance.execution", "==0.1.0"),
    ("assurance.healing", "==0.1.0"),
    ("assurance.quality", "==0.1.0"),
    ("assurance.improvement", "==0.1.0"),
)
_CAPABILITY_PLUGIN_IMPORTS: tuple[tuple[str, str], ...] = (
    ("assurance_intake.plugin", "IntakePlugin"),
    ("assurance_generation.plugin", "GenerationPlugin"),
    ("assurance_execution.plugin", "ExecutionPlugin"),
    ("assurance_healing.plugin", "HealingPlugin"),
    ("assurance_quality.plugin", "QualityPlugin"),
    ("assurance_improvement.plugin", "ImprovementPlugin"),
)
_PROVIDER_MODULE = '''\
"""Authenticated deployment binding provider. Generated by the trusted builder."""

from __future__ import annotations

import json
from importlib.resources import files

from graph_engine import ENGINE_API_VERSION
from graph_engine.canonical import canonical_json_bytes
from graph_engine.plugin_api import (
    CapabilityBindingContribution,
    PluginContribution,
    PluginDependency,
    PluginDescriptor,
    ProviderSource,
    RegistryPorts,
    ResourceContribution,
    validate_contribution,
)


def _document() -> dict[str, object]:
    raw = files(__package__).joinpath("assurance-deployment-plugin.json").read_bytes()
    value = json.loads(raw.decode("utf-8"))
    if not isinstance(value, dict):
        raise ValueError("deployment declaration must be a mapping")
    return value


class DeploymentPlugin:
    @staticmethod
    def descriptor() -> PluginDescriptor:
        document = _document()
        source = ProviderSource.model_validate(document["source"])
        descriptor_doc = document["descriptor"]
        if not isinstance(descriptor_doc, dict):
            raise ValueError("deployment descriptor must be a mapping")
        dependencies = tuple(
            PluginDependency(str(item["plugin_id"]), str(item["version_specifier"]))
            for item in descriptor_doc["dependencies"]
        )
        return PluginDescriptor(
            schema_version="1",
            source=source,
            plugin_id="assurance.product.bindings",
            plugin_version="1.0.0",
            engine_api=ENGINE_API_VERSION,
            task_handlers=(),
            commit_validators=(),
            dependencies=dependencies,
            schemas=(),
            resources=tuple(str(item) for item in descriptor_doc["resources"]),
            effects=(),
            bindings=tuple(str(item) for item in descriptor_doc["bindings"]),
        )

    @staticmethod
    def contribute(ports: RegistryPorts) -> PluginContribution:
        if ports.engine_api != ENGINE_API_VERSION:
            raise ValueError(f"unsupported engine API: {ports.engine_api!r}")
        document = _document()
        contribution_doc = document["contribution"]
        if not isinstance(contribution_doc, dict):
            raise ValueError("deployment contribution must be a mapping")
        bindings = tuple(
            CapabilityBindingContribution(
                capability_id=str(item["capability_id"]),
                target_capability_id=str(item["target_capability_id"]),
                data=item["data"],
                resource_ids=tuple(str(resource_id) for resource_id in item["resource_ids"]),
                secret_handles=tuple(str(handle) for handle in item["secret_handles"]),
            )
            for item in contribution_doc["bindings"]
        )
        resources = tuple(
            ResourceContribution(
                resource_id=str(item["resource_id"]),
                media_type=str(item["media_type"]),
                content=canonical_json_bytes(item["content"]),
            )
            for item in contribution_doc["resources"]
        )
        contribution = PluginContribution(bindings=bindings, resources=resources)
        validate_contribution(DeploymentPlugin.descriptor(), contribution)
        return contribution
'''


class BindingBuildError(ValueError):
    """Raised when a deployment binding wheel cannot be built safely."""


@dataclass(frozen=True)
class _RenderedWheel:
    manifest_digest: str
    distribution: str
    import_package: str
    declaration_path: str
    entry_point_value: str
    wheel_name: str
    members: dict[str, bytes]


def canonical_wheel_filename(distribution: str, version: str) -> str:
    escaped = re.sub(r"[^A-Za-z0-9]+", "_", distribution).strip("_")
    return f"{escaped}-{version}-py3-none-any.whl"


def build_deployment_wheel(manifest_path: Path, output_dir: Path) -> BuiltDeploymentWheel:
    document = _load_manifest_document(manifest_path)
    bindings = DeploymentBindingsV1.model_validate(document)
    _reject_capability_source_drift()
    _require_empty_output_dir(output_dir)
    rendered = _render_wheel_contents(bindings)
    output_dir.mkdir(parents=True, exist_ok=True)
    wheel_path = output_dir / rendered.wheel_name
    _write_deterministic_wheel(wheel_path, rendered.members)
    wheel_bytes = wheel_path.read_bytes()
    return BuiltDeploymentWheel(
        wheel=wheel_path,
        manifest_digest=rendered.manifest_digest,
        wheel_digest=_sha256_digest(wheel_bytes),
        distribution=rendered.distribution,
        import_package=rendered.import_package,
        entry_point_value=rendered.entry_point_value,
        declaration_path=rendered.declaration_path,
        plugin_id=PLUGIN_ID,
        plugin_version=PLUGIN_VERSION,
    )


def _load_manifest_document(manifest_path: Path) -> dict[str, object]:
    try:
        raw = manifest_path.read_text(encoding="utf-8")
    except OSError as error:
        raise BindingBuildError(f"cannot read deployment manifest: {manifest_path}") from error
    try:
        value = yaml.safe_load(raw)
    except yaml.YAMLError as error:
        raise BindingBuildError("deployment manifest is not valid YAML") from error
    if not isinstance(value, dict):
        raise BindingBuildError("deployment manifest must be a complete mapping")
    return value


def _require_empty_output_dir(output_dir: Path) -> None:
    if not output_dir.exists():
        return
    if not output_dir.is_dir() or any(output_dir.iterdir()):
        raise BindingBuildError("output directory must be empty")


def _reject_capability_source_drift() -> None:
    live_prepares, live_finalizes = _live_prepare_and_finalize_ids()
    if live_prepares != frozenset(PREPARE_IDS) or live_finalizes != expected_finalize_ids():
        raise BindingBuildError("source drift: installed prepare/finalize closure")


def _live_prepare_and_finalize_ids() -> tuple[frozenset[str], frozenset[str]]:
    handlers: list[str] = []
    for module_name, attribute in _CAPABILITY_PLUGIN_IMPORTS:
        module = __import__(module_name, fromlist=[attribute])
        plugin = getattr(module, attribute)
        handlers.extend(plugin.descriptor().task_handlers)
    prepares = frozenset(handler for handler in handlers if handler.endswith(".prepare"))
    finalizes = frozenset(handler for handler in handlers if handler.endswith(".finalize"))
    return prepares, finalizes


def _render_wheel_contents(bindings: DeploymentBindingsV1) -> _RenderedWheel:
    manifest_digest = _sha256_digest(canonical_json_bytes(bindings.model_dump(mode="json")))
    prefix = manifest_digest.removeprefix("sha256:")[:16]
    distribution = f"assurance-product-bindings-{prefix}"
    import_package = f"assurance_product_bindings_{prefix}"
    _assert_safe_zip_name(import_package)
    declaration_path = f"{import_package}/assurance-deployment-plugin.json"
    entry_point_value = f"{import_package}.provider:DeploymentPlugin"
    wheel_name = canonical_wheel_filename(distribution, PLUGIN_VERSION)
    dist_info = f"{Path(wheel_name).stem.replace('-py3-none-any', '')}.dist-info"
    declaration = _render_declaration(
        bindings,
        distribution=distribution,
        declaration_path=declaration_path,
        entry_point_value=entry_point_value,
    )
    members = {
        f"{import_package}/__init__.py": b'"""Authenticated Assurance deployment bindings."""\n',
        f"{import_package}/provider.py": _PROVIDER_MODULE.encode("utf-8"),
        declaration_path: canonical_json_bytes(cast(JSONValue, declaration)) + b"\n",
        f"{dist_info}/METADATA": _metadata_bytes(distribution),
        f"{dist_info}/WHEEL": (
            "Wheel-Version: 1.0\n"
            "Generator: assurance-product-binding-builder/1.0.0\n"
            "Root-Is-Purelib: true\n"
            "Tag: py3-none-any\n"
        ).encode("utf-8"),
        f"{dist_info}/entry_points.txt": (
            f"[graph_engine.plugins]\ndeployment = {entry_point_value}\n"
        ).encode("utf-8"),
    }
    for name in members:
        _assert_safe_zip_name(name)
    return _RenderedWheel(
        manifest_digest=manifest_digest,
        distribution=distribution,
        import_package=import_package,
        declaration_path=declaration_path,
        entry_point_value=entry_point_value,
        wheel_name=wheel_name,
        members=members,
    )


def _render_declaration(
    bindings: DeploymentBindingsV1,
    *,
    distribution: str,
    declaration_path: str,
    entry_point_value: str,
) -> dict[str, object]:
    source = {
        "distribution": distribution,
        "version": PLUGIN_VERSION,
        "entrypoint_group": "graph_engine.plugins",
        "entrypoint_name": "deployment",
        "entrypoint_value": entry_point_value,
        "declaration_path": declaration_path,
        "import_roots": [""],
    }
    resources = _resource_documents(bindings)
    binding_docs = _binding_documents(bindings)
    resource_ids = tuple(item["resource_id"] for item in resources)
    binding_ids = tuple(item["capability_id"] for item in binding_docs)
    dependencies = [
        {"plugin_id": plugin_id, "version_specifier": specifier}
        for plugin_id, specifier in (
            *_CAPABILITY_DEPENDENCIES,
            (bindings.runtime_plugin_id, "==0.1.0"),
        )
    ]
    return {
        "kind": "plugin",
        "schema_version": "1",
        "source": source,
        "descriptor": {
            "schema_version": "1",
            "plugin_id": PLUGIN_ID,
            "plugin_version": PLUGIN_VERSION,
            "engine_api": ENGINE_API,
            "source": source,
            "dependencies": dependencies,
            "task_handlers": [],
            "commit_validators": [],
            "schemas": [],
            "effects": [],
            "resources": list(resource_ids),
            "bindings": list(binding_ids),
        },
        "contribution": {
            "bindings": list(binding_docs),
            "resources": list(resources),
        },
    }


def _resource_documents(bindings: DeploymentBindingsV1) -> tuple[dict[str, object], ...]:
    documents: list[dict[str, object]] = []
    for resource_id, profile in sorted(bindings.permission_profiles.items()):
        documents.append(
            {
                "resource_id": resource_id,
                "media_type": "application/json",
                "content": profile.model_dump(mode="json"),
            }
        )
    for resource_id, policy in sorted(bindings.request_policies.items()):
        documents.append(
            {
                "resource_id": resource_id,
                "media_type": "application/json",
                "content": policy.model_dump(mode="json"),
            }
        )
    return tuple(sorted(documents, key=lambda item: str(item["resource_id"])))


def _binding_documents(bindings: DeploymentBindingsV1) -> tuple[dict[str, object], ...]:
    adapter_data = bindings.adapter_binding.model_dump(mode="json")
    execute_target = f"{bindings.runtime_plugin_id}.execute"
    secret_handles = list(adapter_secret_handles(bindings.adapter_binding))
    documents: list[dict[str, object]] = []
    for prepare_id in PREPARE_IDS:
        assignment = bindings.routes[prepare_id]
        prepare_alias, execute_alias, finalize_alias = alias_ids_for_prepare(prepare_id)
        stem = prepare_id.removesuffix(".prepare")
        permission_digest = canonical_digest(
            bindings.permission_profiles[assignment.permission_profile_id].model_dump(mode="json")
        )
        policy_digest = canonical_digest(
            bindings.request_policies[assignment.request_policy_id].model_dump(mode="json")
        )
        request_config_digest = canonical_digest(
            {
                "adapter_plugin_id": bindings.runtime_plugin_id,
                "adapter_configuration_digest": bindings.adapter_binding.adapter_configuration_digest,
                "provider_model": assignment.provider_model,
                "worker_profile": assignment.worker_profile,
                "permission_profile_digest": permission_digest,
                "request_policy_digest": policy_digest,
                "capability_binding_id": prepare_alias,
            }
        )
        documents.append(
            {
                "capability_id": prepare_alias,
                "target_capability_id": prepare_id,
                "data": {
                    "execution": {
                        "provider_model": assignment.provider_model,
                        "worker_profile": assignment.worker_profile,
                        "permission_profile_digest": permission_digest,
                        "limits": assignment.limits.model_dump(mode="json"),
                    },
                    "request_policy_digest": policy_digest,
                    "request_config_digest": request_config_digest,
                },
                "resource_ids": [
                    assignment.permission_profile_id,
                    assignment.request_policy_id,
                ],
                "secret_handles": [],
            }
        )
        documents.append(
            {
                "capability_id": execute_alias,
                "target_capability_id": execute_target,
                "data": adapter_data,
                "resource_ids": [],
                "secret_handles": secret_handles,
            }
        )
        documents.append(
            {
                "capability_id": finalize_alias,
                "target_capability_id": f"{stem}.finalize",
                "data": None,
                "resource_ids": [],
                "secret_handles": [],
            }
        )
    return tuple(sorted(documents, key=lambda item: str(item["capability_id"])))


def _metadata_bytes(distribution: str) -> bytes:
    requirements = [
        "graph-engine==0.1.0",
        *(f"{name}==0.1.0" for name, _ in _CAPABILITY_DEPENDENCIES),
    ]
    lines = [
        "Metadata-Version: 2.1",
        f"Name: {distribution}",
        f"Version: {PLUGIN_VERSION}",
        "Summary: Authenticated Assurance deployment binding wheel",
        "Requires-Python: >=3.11",
        *(f"Requires-Dist: {requirement}" for requirement in requirements),
        "",
    ]
    return "\n".join(lines).encode("utf-8")


def _write_deterministic_wheel(wheel_path: Path, members: Mapping[str, bytes]) -> None:
    record_name = next(name for name in members if name.endswith(".dist-info/METADATA")).replace(
        "METADATA", "RECORD"
    )
    _assert_safe_zip_name(record_name)
    record_lines = [
        f"{name},{_record_hash(content)},{len(content)}" for name, content in sorted(members.items())
    ]
    record_lines.append(f"{record_name},,")
    record_bytes = ("\n".join(record_lines) + "\n").encode("utf-8")
    ordered = dict(sorted(members.items()))
    ordered[record_name] = record_bytes
    names = [name for name in ordered if name != record_name]
    names.append(record_name)
    with ZipFile(wheel_path, "w") as archive:
        for name in names:
            info = ZipInfo(filename=name, date_time=_WHEEL_EPOCH)
            info.compress_type = ZIP_DEFLATED
            info.create_system = 3
            info.external_attr = _FILE_MODE << 16
            archive.writestr(info, ordered[name], compress_type=ZIP_DEFLATED, compresslevel=9)


def _record_hash(content: bytes) -> str:
    digest = hashlib.sha256(content).digest()
    return "sha256=" + base64.urlsafe_b64encode(digest).decode("ascii").rstrip("=")


def _sha256_digest(content: bytes) -> str:
    return "sha256:" + hashlib.sha256(content).hexdigest()


def _assert_safe_zip_name(name: str) -> None:
    if not name or "\\" in name or name.startswith("/") or name.endswith("/"):
        raise BindingBuildError("ZIP path escape")
    path = PurePosixPath(name)
    if path.is_absolute() or path.as_posix() != name or any(part in {"", ".", ".."} for part in path.parts):
        raise BindingBuildError("ZIP path escape")
